-- ========================= --
--      db_script_string     --
-- ========================= --



ALTER TABLE `db_script_string` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;

UPDATE `db_script_string` SET `content_loc7`='Entra al Círculo de Sangre, $N. ¡La pelea está a punto de empezar!' WHERE entry=2000000001;
UPDATE `db_script_string` SET `content_loc7`='¡La batalla está a punto de comenzar!' WHERE entry=2000000002;
UPDATE `db_script_string` SET `content_loc7`='¡$N contra el feroz uñagrieta, Dedorroto!' WHERE entry=2000000003;
UPDATE `db_script_string` SET `content_loc7`='¿Todos se divierten hasta ahora? ¡Genial! Bienvenidos a la Feria de la Luna Negra, ¡el mayor espectáculo de todo Azeroth! Asegúrense de hablar con Yebb y sus amigos aquí mientras se deleitan con el extraño zoologico Luna Negra de Tesorillos.' WHERE entry=2000000004;
UPDATE `db_script_string` SET `content_loc7`='¡Estamos de vuelta y mejor que nunca! Es la Feria de la Luna Negra amigo, ¡y es tu día de suerte! Sin escatimar en gastos, hemos reunido maravillas y rarezas de todo el mundo para su deleite. Seas joven o viejo, rico o pobre, ¡la Feria de la Luna Negra lo tiene todo! Asegúrate de canjear tus vales de la Feria de la Luna Negra con Gelvas Roñoso, y elige entre varios exóticos y maravillosos premios!' WHERE entry=2000000005;
UPDATE `db_script_string` SET `content_loc7`='Venga, vengan todos. ¡Bienvenidos a la Feria de la Luna Negra! No sean tímidos. Pasen por Lhara y compren un artefacto exótico de lejanas tierras. Si eres uno de los pocos afortunados que han encontrado Naipes de la Luna Negra, una palabra con el profesor Paleo. ¿Tienes hambre? ¿Sed? ¡Estás de suerte! Hay refrigerios disponibles justo aquí, con Sylannia y Stamp. Recomiendo la Gran reserva de la Luna Negra sobre algunas Alitas súper picantes. Y si el futuro es lo que buscas, entonces corre, no camines, para hablar con Sayge.' WHERE entry=2000000006;
UPDATE `db_script_string` SET `content_loc7`='Bienvenidos todos a la Feria de la Luna Negra, ¡el evento más grande en todo el mundo! Tenemos de todo ... ¡comida deliciosa, bebidas fuertes, artefactos exóticos, lecturas de la suerte, premios increíbles y emociones sin fin! ¡No te olvides de canjear tus vales de la Feria de la Luna Negra con Gelvas Roñoso! Todo lo que pide son cinco o más y ya estarás recibiendo los premios más maravillosos de todo Azeroth. ¡Todo el mundo gana!' WHERE entry=2000000007;
UPDATE `db_script_string` SET `content_loc7`='¡Estamos de vuelta y mejor que nunca! Es la Feria de la Luna Negra amigo, ¡y es tu día de suerte! Sin escatimar en gastos, hemos reunido maravillas y rarezas de todo el mundo para su deleite. Seas joven o viejo, rico o pobre, ¡la Feria de la Luna Negra lo tiene todo! Asegúrate de canjear tus vales de la Feria de la Luna Negra con Gelvas Roñoso, y elige entre varios exóticos y maravillosos premios!' WHERE entry=2000000008;
UPDATE `db_script_string` SET `content_loc7`='¿Qué ocurre?' WHERE entry=2000000009;
UPDATE `db_script_string` SET `content_loc7`='¿Volcor necesita ayuda?' WHERE entry=2000000010;
UPDATE `db_script_string` SET `content_loc7`='Está bien, voy a encontrar gente para ayudarle.' WHERE entry=2000000011;
UPDATE `db_script_string` SET `content_loc7`='Está bien, vamos.' WHERE entry=2000000012;
UPDATE `db_script_string` SET `content_loc7`='¡Oh no! ¡Están aquí!' WHERE entry=2000000013;
UPDATE `db_script_string` SET `content_loc7`='Oh, hola Zarpadura.' WHERE entry=2000000014;
UPDATE `db_script_string` SET `content_loc7`='Vale, $N. Ya puedo ir solo hasta Auberdine. Ve con Terenthis. Te está esperando. Gracias por la ayuda.' WHERE entry=2000000015;
UPDATE `db_script_string` SET `content_loc7`='Vale, buena suerte $Gamigo:amiga;. Gracias por la ayuda.' WHERE entry=2000000016;
UPDATE `db_script_string` SET `content_loc7`='Está bien, ¡vámonos!' WHERE entry=2000000017;
UPDATE `db_script_string` SET `content_loc7`='Puedo continuar el resto del camino, $N. ¡GRACIAS!' WHERE entry=2000000018;
UPDATE `db_script_string` SET `content_loc7`='Paciencia $N. La antorcha está casi completa.' WHERE entry=2000000019;
UPDATE `db_script_string` SET `content_loc7`='Qué interesante...' WHERE entry=2000000020;
UPDATE `db_script_string` SET `content_loc7`='Necesito consultar con Noram y Horatio.' WHERE entry=2000000021;
UPDATE `db_script_string` SET `content_loc7`='¡Mira! ¡Los esbirros de Terokk se acercan!' WHERE entry=2000000022;
UPDATE `db_script_string` SET `content_loc7`='¡Mira! ¡Vienen más!' WHERE entry=2000000023;
UPDATE `db_script_string` SET `content_loc7`='¡Y aún más!' WHERE entry=2000000024;
UPDATE `db_script_string` SET `content_loc7`='¡Un Avatar de Terokk! ¡A las armas!' WHERE entry=2000000025;
UPDATE `db_script_string` SET `content_loc7`='¡Vaya!' WHERE entry=2000000026;
UPDATE `db_script_string` SET `content_loc7`='El Pueblo de Páramos de Poniente te saluda $N, un bravo y valiente defensor de la libertad.' WHERE entry=2000000028;
UPDATE `db_script_string` SET `content_loc7`='Continúa, $N. Pronto comenzará la invocación...' WHERE entry=2000000029;
UPDATE `db_script_string` SET `content_loc7`='¡Eso tiene sentido!' WHERE entry=2000000030;
UPDATE `db_script_string` SET `content_loc7`='¡Tu cuerpo es mío! ¡Nuestros destinos estarán unidos para siempre!' WHERE entry=2000000031;
UPDATE `db_script_string` SET `content_loc7`='Cíñete $N, el demonio de esta esfera es una bestia vil.' WHERE entry=2000000032;
UPDATE `db_script_string` SET `content_loc7`='¡Sigan moviéndose!' WHERE entry=2000000033;
UPDATE `db_script_string` SET `content_loc7`='Ven, $N. Lord Tempestira aguarda.' WHERE entry=2000000034;
UPDATE `db_script_string` SET `content_loc7`='¡Guerreros Faucedracos, acérquense! ¡Uno de ustedes ha alcanzado el rango de Alto Señor! ¡Inclinen sus cabezas en reverencia! Muestren respeto y fidelidad al Alto Señor $N!' WHERE entry=2000000035;
UPDATE `db_script_string` SET `content_loc7`='Lord Illidan estará aquí pronto.' WHERE entry=2000000036;
UPDATE `db_script_string` SET `content_loc7`='¡Toda la gloria a Lord Illidan!' WHERE entry=2000000037;
UPDATE `db_script_string` SET `content_loc7`='Lord Illidan, este es el Faucedraco que yo, y los demás, te hemos hablado. ¡Él nos conducirá a la victoria!' WHERE entry=2000000038;
UPDATE `db_script_string` SET `content_loc7`='Pero... Mi lord, No lo entiendo. $N... Él es el orco que ha...' WHERE entry=2000000039;
UPDATE `db_script_string` SET `content_loc7`='Así se hará, mi lord.' WHERE entry=2000000040;
UPDATE `db_script_string` SET `content_loc7`='Así que pensaste en ridiculizar a Mor''ghor, ¿eh? Antes de que seas llevado ante Lord Illidan, sentirás un dolor que no sabías que existía. Disfrutaré en obtener mi propia venganza.' WHERE entry=2000000041;
UPDATE `db_script_string` SET `content_loc7`='Hasta que nos volvamos a encontrar, valiente guerrero.' WHERE entry=2000000042;
UPDATE `db_script_string` SET `content_loc7`='%s comienza el conjuro de invocación...' WHERE entry=2000000043;
UPDATE `db_script_string` SET `content_loc7`='Está hecho...' WHERE entry=2000000044;
UPDATE `db_script_string` SET `content_loc7`='¡No hay nada como una infusión de albaza hirviendo en un día frío en Dun Morogh para conseguir que todo empiece bien!' WHERE entry=2000000045;
UPDATE `db_script_string` SET `content_loc7`='¡Oh oh oh caliente, caliente, caliente! Si esto no trajo la primavera a tus pies, ¡entonces no sé que será!' WHERE entry=2000000046;
UPDATE `db_script_string` SET `content_loc7`='¡Croac! ¡¡No!! ¡Esto no puede ser, croac! ¡Me has embaucado con tus artimañas, croac! ¡Croac!' WHERE entry=2000000047;
UPDATE `db_script_string` SET `content_loc7`='Pongamos esta extraña tierra en mi maceta...' WHERE entry=2000000048;
UPDATE `db_script_string` SET `content_loc7`='Gracias de nuevo, $N. Esta extraña tierra me resultará muy útil para mis experimentos.' WHERE entry=2000000049;
UPDATE `db_script_string` SET `content_loc7`='Hola Zarpadura' WHERE entry=2000000050;
UPDATE `db_script_string` SET `content_loc7`='¿Qué ocurre?' WHERE entry=2000000051;
UPDATE `db_script_string` SET `content_loc7`='¿Volcor se había ido?' WHERE entry=2000000052;
UPDATE `db_script_string` SET `content_loc7`='¿Sabes en donde está?' WHERE entry=2000000053;
UPDATE `db_script_string` SET `content_loc7`='Está bien. Ahora estoy enviando gente. Tenemos que encontrarlo y ayudarlo.' WHERE entry=2000000054;
UPDATE `db_script_string` SET `content_loc7`='¿Cuántos brutos más tengo que enviar de nuevo a mamá y papá en bolsas antes de que desarrolles un cerebro capaz de entender que un escuadrón de muerte de la Legión son suicidas? ¡Y no me asientan con sus torpes calaveras como si supieran de lo que estoy hablando!' WHERE entry=2000000055;
UPDATE `db_script_string` SET `content_loc7`='¡Oye, Belm! Dáme una jarra de Cerveza del Trueno, y otra para mi $gbuen amigo:buena amiga; $N.' WHERE entry=2000000056;
UPDATE `db_script_string` SET `content_loc7`='Espíritus del Agua, los alabo, y les ruego un favor. Han escuchado los motivos de $N, y confío en que su intención es noble. Por favor, ¿nos ayudan?' WHERE entry=2000000057;
UPDATE `db_script_string` SET `content_loc7`='Gracias gran espíritu. ¡Gracias!' WHERE entry=2000000058;
UPDATE `db_script_string` SET `content_loc7`='Retírate, $N' WHERE entry=2000000059;
UPDATE `db_script_string` SET `content_loc7`='¡Por las estrellas! ¡Ha sido invocado un espíritu!' WHERE entry=2000000060;
UPDATE `db_script_string` SET `content_loc7`='¡Es un misterio del pasado, en efecto! ¡Pero una clave de nuestro futuro!' WHERE entry=2000000061;
UPDATE `db_script_string` SET `content_loc7`='¡La amenaza haber terminado! ¡$N habernos salvado!' WHERE entry=2000000062;
UPDATE `db_script_string` SET `content_loc7`='Sígueme, $gbuen:buena; $C. Tendré su barda hecha más rápido de lo que tardaría en terminarme una cerveza negra enana. Mmmm... cerveza negra.' WHERE entry=2000000063;
UPDATE `db_script_string` SET `content_loc7`='Bueno, eso debería funcionar. Vamos, ¡volvamos a la tienda para terminar nuestro negocio!' WHERE entry=2000000064;
UPDATE `db_script_string` SET `content_loc7`='¡No permitiremos ningún sirviente de demonios en nuestras tierras!' WHERE entry=2000000065;
UPDATE `db_script_string` SET `content_loc7`='La paz y la paciencia sea contigo, $N. Siendo siempre fuerte.' WHERE entry=2000000066;
UPDATE `db_script_string` SET `content_loc7`='¿Qué haces en el reino de Ysera, intruso? Dejanos, ¡te lo digo! ¡Tu clase no es bienvenida aquí!' WHERE entry=2000000067;
UPDATE `db_script_string` SET `content_loc7`='¡Tú... tú no eres uno de ellos! ¡Salgamos de su vista antes de que nos encuentren! ¡De prisa!' WHERE entry=2000000068;
UPDATE `db_script_string` SET `content_loc7`='¡Me están siguiendo, $R! Rápido, dime porqué estás aquí antes de que nos descubran! Si me capturan, significará mi muerte y la tuya.' WHERE entry=2000000069;
UPDATE `db_script_string` SET `content_loc7`='Habría tardado años en encontrar el Libro del Cuervo sin ti, joven gavilán. Vuelve a tu hogar en Nagrand con nuestra gratitud.' WHERE entry=2000000070;
UPDATE `db_script_string` SET `content_loc7`='¡Este es! ¡Este realmente es... el Libro del Cuervo!' WHERE entry=2000000071;
UPDATE `db_script_string` SET `content_loc7`='Todo está aquí... \"así como los seguidores del cuervo capturados y los sprints de los rivales sometidos, ¡atrápenlos para siempre dentro de estatuas de piedra!\" La tabla incluso menciona el nombre del dios cuervo: Anzu. ¡Yo pensé que estaba perdido para la historia!' WHERE entry=2000000072;
UPDATE `db_script_string` SET `content_loc7`='Hay algo más, también. Después de la descripción de una batalla sangrienta y la caída del cuervo, hay una profecía. Anzu perseguirá el sueño de sus enemigos, tornándolos en un influir de un retorno a este mundo...' WHERE entry=2000000073;
UPDATE `db_script_string` SET `content_loc7`='La tabla tiene la confirmación que necesitamos, tal como lo pensé. Ahora, ¡tenemos que usar esta información para acabar y derrotar a este Anzu antes de que cause más daño al Sueño Esmeralda!' WHERE entry=2000000074;
UPDATE `db_script_string` SET `content_loc7`='Desde que los gavilanes han demostrado éxito en la caza de las piedras del cuervo, la vigía Elaira ha entrenado a otro para transmitir mi voz a gran distancia. ¡Él puede ayudarnos a comunicar lo que investigues sobre los espíritus de las aves reveladas en la tabla!' WHERE entry=2000000075;
UPDATE `db_script_string` SET `content_loc7`='¡Oigan, habitantes de Tanaris! Séales sabido que $N es un miembro exaltado de la Orden del Mitril. Un herrero de honor, dedicación, y de infinita paciencia. ¡Tres hurras por $N!' WHERE entry=2000000076;
UPDATE `db_script_string` SET `content_loc7`='Abuela Viento de Halcón hace gestos al cántaro de agua colocada al borde del pozo.' WHERE entry=2000000077;
UPDATE `db_script_string` SET `content_loc7`='¿Como va a vigilar el barril...?' WHERE entry=2000000078;
UPDATE `db_script_string` SET `content_loc7`='Bueno, de vuelta a mis asuntos. Pero seguro que fue bueno tomar ese descanso, ¡y siempre es bueno beberse una cerveza del Trueno!' WHERE entry=2000000079;
UPDATE `db_script_string` SET `content_loc7`='Esto no debería tardar demasiado...' WHERE entry=2000000080;
UPDATE `db_script_string` SET `content_loc7`='El licor de la invisibilidad ya está listo, $N.' WHERE entry=2000000081;
UPDATE `db_script_string` SET `content_loc7`='Yo... no me siento... muy... bien...' WHERE entry=2000000082;
UPDATE `db_script_string` SET `content_loc7`='Mi mente... mi carne... ¡me estoy descomponiendo...!' WHERE entry=2000000083;
UPDATE `db_script_string` SET `content_loc7`='¡Alzo mi cerveza y espero liberarme de los de tu calaña! No tan buen canalla, $N. ¡Salud!' WHERE entry=2000000084;
UPDATE `db_script_string` SET `content_loc7`='Toma una vela de señalización de este cajón, $N.' WHERE entry=2000000085;
UPDATE `db_script_string` SET `content_loc7`='Denalan quita las semillas de la fruta resplandeciente...' WHERE entry=2000000086;
UPDATE `db_script_string` SET `content_loc7`='Vamos a ver cómo estas semillas crecen en mi tierra preparada ...' WHERE entry=2000000087;
UPDATE `db_script_string` SET `content_loc7`='Denalan planta las semillas de la fruta.' WHERE entry=2000000088;
UPDATE `db_script_string` SET `content_loc7`='¡Bogono crece desde la tierra!' WHERE entry=2000000089;
UPDATE `db_script_string` SET `content_loc7`='Onus estudia el pergamino del Escrito Crepuscular...' WHERE entry=2000000090;
UPDATE `db_script_string` SET `content_loc7`='¡Onus es golpeado por la magia desatada!' WHERE entry=2000000091;
UPDATE `db_script_string` SET `content_loc7`='Mmm...' WHERE entry=2000000092;
UPDATE `db_script_string` SET `content_loc7`='Denalan se apresura a su maceta.' WHERE entry=2000000093;
UPDATE `db_script_string` SET `content_loc7`='Espero que esta fronda eche raíces...' WHERE entry=2000000094;
UPDATE `db_script_string` SET `content_loc7`='Zarlman Dos Lunas comienza cantando mientras mezcla las piedras y el ambercom ente elFuego Tribal.' WHERE entry=2000000095;
UPDATE `db_script_string` SET `content_loc7`='El agua de los Videntes está listo para su consumo, $N.' WHERE entry=2000000096;
UPDATE `db_script_string` SET `content_loc7`='Tonga Tótem de Runa inspecciona las conchas de Quijaforte...' WHERE entry=2000000097;
UPDATE `db_script_string` SET `content_loc7`='Mmm...' WHERE entry=2000000098;
UPDATE `db_script_string` SET `content_loc7`='Extraño. Muy extraño...' WHERE entry=2000000099;
UPDATE `db_script_string` SET `content_loc7`='$N. Estas conchas me dicen mucho, pero me temo que plantean otras muchas preguntas...' WHERE entry=2000000100;
UPDATE `db_script_string` SET `content_loc7`='Muy bien, echémosle un vistazo a esto...' WHERE entry=2000000101;
UPDATE `db_script_string` SET `content_loc7`='Oh, darn...' WHERE entry=2000000102;
UPDATE `db_script_string` SET `content_loc7`='Vale, ¡empecemos!' WHERE entry=2000000103;
UPDATE `db_script_string` SET `content_loc7`='...ups.' WHERE entry=2000000104;
UPDATE `db_script_string` SET `content_loc7`='Los espíritus del Espolón siguen causando estragos, $N.' WHERE entry=2000000105;
UPDATE `db_script_string` SET `content_loc7`='Me temo que nunca podremos calmarlos...' WHERE entry=2000000106;
UPDATE `db_script_string` SET `content_loc7`='Estos no son rastros de Shango.' WHERE entry=2000000107;
UPDATE `db_script_string` SET `content_loc7`='Estos rastros deben pertenecer a Shango.' WHERE entry=2000000108;
UPDATE `db_script_string` SET `content_loc7`='¡Sólo me queda por destruir estos instrumentos del mal! ¡Por la Horda!' WHERE entry=2000000138;
UPDATE `db_script_string` SET `content_loc7`='Pobre Dorius. Si alguna vez tengo en mis manos a los Hierro Negro, así que ayúdame...' WHERE entry=2000005000;
UPDATE `db_script_string` SET `content_loc7`='Opus quiere oro de Cuergo... con gusanos.' WHERE entry=2000005001;
UPDATE `db_script_string` SET `content_loc7`='¡Bijou perdido! ¡CUAC! <cof>' WHERE entry=2000005002;
UPDATE `db_script_string` SET `content_loc7`='Kibler está siendo investigado por la G.E.T.A.' WHERE entry=2000005003;
UPDATE `db_script_string` SET `content_loc7`='Bijou sabe donde están escondidos los tesoros.' WHERE entry=2000005004;
UPDATE `db_script_string` SET `content_loc7`='¿¡Dragones controlando orcos!? ¡CUAC!' WHERE entry=2000005005;
UPDATE `db_script_string` SET `content_loc7`='Todos van a la Cumbre pero ninguno regresa jamás... al igual que Bijou.' WHERE entry=2000005006;
UPDATE `db_script_string` SET `content_loc7`='¡Pregunta a Kibler sobre el tesoro! ¡CUAC!' WHERE entry=2000005007;
UPDATE `db_script_string` SET `content_loc7`='¡¡CUAC!! <cof> <cof> ¡Necesito dejar de fumar!' WHERE entry=2000005008;
UPDATE `db_script_string` SET `content_loc7`='¡Bien hecho, soldados! ¡Descansen!' WHERE entry=2000005009;
UPDATE `db_script_string` SET `content_loc7`='¡Zug zug! ¡Feliz de ayudar!' WHERE entry=2000005010;
UPDATE `db_script_string` SET `content_loc7`='¡Sí, de inmediato mamá!' WHERE entry=2000005011;
UPDATE `db_script_string` SET `content_loc7`='Extrañas pisadas, escudos quemados, insignias perdidas... ¿cómo darle sentido a todo esto?' WHERE entry=2000005012;
UPDATE `db_script_string` SET `content_loc7`='No creo que Drazzit vaya a tener suerte en encontrar a alguien que mate a este raptor. Quiero decir, él ya dobló la recompensa...' WHERE entry=2000005013;
UPDATE `db_script_string` SET `content_loc7`='¡Pero este es el único lugar en el que cabe Brogg! ¡Los Goblins construyen estructuras tan pequeñas!' WHERE entry=2000005014;
UPDATE `db_script_string` SET `content_loc7`='Creo que ya discutimos esto, Brogg. No puedes quedarte en este lugar. Claro, esto puede alojarte, ¡pero no hay espacio para nadie más!' WHERE entry=2000005015;
UPDATE `db_script_string` SET `content_loc7`='Sí, hemos dicho que puedes quedarte aquí, ¡pero este lugar es nuestro cuartel general! ¡Todos nuestros manuales y diseños se guardan aquí!' WHERE entry=2000005016;
UPDATE `db_script_string` SET `content_loc7`='Me inclino a decir que hicieron a los ogros demasiado grandes. Ya veo que no voy a convencerte de que te mudes ahora, pero no creo que esto sea permanente.' WHERE entry=2000005017;
UPDATE `db_script_string` SET `content_loc7`='Ah, esto debe ser él ahora... ¿no?' WHERE entry=2000005018;
UPDATE `db_script_string` SET `content_loc7`='Es posible que desees dar un paso atrás. Destripar el pescado es un trabajo sucio.' WHERE entry=2000005019;
UPDATE `db_script_string` SET `content_loc7`='Es bueno verte defendiendo Theramore con orgullo, $gamigo:amiga;.' WHERE entry=2000005020;
UPDATE `db_script_string` SET `content_loc7`='Cuando acabe tu turno, vamos a ir a la posada. Voy a comprar una ronda y podremos recordar aquellos buenos viejos tiempos.' WHERE entry=2000005021;
UPDATE `db_script_string` SET `content_loc7`='¿No te gustaría volver a esos días? Tengo unos amigos que conocen la manera de hacerlo.' WHERE entry=2000005022;
UPDATE `db_script_string` SET `content_loc7`='Cada artículo que tengo a la venta lo he adquirido. Tiene mi garantía personal de autenticidad.' WHERE entry=2000005023;
UPDATE `db_script_string` SET `content_loc7`='¡Se escapa!' WHERE entry=2000005024;
UPDATE `db_script_string` SET `content_loc7`='¡Premios! ¡Obtengan sus premios aquí! ¡Vengan aquí y canjeen sus vales de la Feria de la Luna Negra por valiosos premios!' WHERE entry=2000005025;
UPDATE `db_script_string` SET `content_loc7`='Ven y habla conmigo, y lo que antes estaba nublado se verá tan claro como el cristal.' WHERE entry=2000005026;
UPDATE `db_script_string` SET `content_loc7`='Las fuerzas del Rey Exánime están construyendo. Es imperativo que nuestro horario esté en armonía con sus planes.' WHERE entry=2000005027;
UPDATE `db_script_string` SET `content_loc7`='Mañana vamos a comenzar el entrenamiento de nuestros dragones prometedores, así que no olvides tu juguetes para masticar.' WHERE entry=2000005028;
UPDATE `db_script_string` SET `content_loc7`='Nuestra más antigua garra de dragones está aún muy lejos de la madurez, pero con paciencia y estudio, estamos seguros de que los dragones pronto estarán listos.' WHERE entry=2000005029;
UPDATE `db_script_string` SET `content_loc7`='Si esperas a venir a verme, ¡puede que no quede nada más!' WHERE entry=2000005030;
UPDATE `db_script_string` SET `content_loc7`='Vengo de la tierra de abajo... donde las mujeres plagan y los hombres dividen.' WHERE entry=2000005031;
UPDATE `db_script_string` SET `content_loc7`='...Y entonces el tauren dijo, \"¡13 PULGADAS!\"' WHERE entry=2000005032;
UPDATE `db_script_string` SET `content_loc7`='¡Venga, vengan todos! ¡Bienvenidos a la Feria de la Luna Negra! ¿Se te antoja una aventura? ¿Buscas tesoros exóticos y misteriosos? ¡Entonces no busques más! Tú, mi $Gamigo:amiga;, ¡has venido al lugar indicado! ¡Sumérgete y toma parte en todo lo que la Feria tiene para ofrecer! Vamos a estar en este lugar toda la semana, ¡así que asegúrense de decirselo a sus amigos y seres queridos!' WHERE entry=2000005033;
UPDATE `db_script_string` SET `content_loc7`='¡Bienvenidos todos y cada uno a la Feria de la Luna Negra, el más grande evento de todos los mundos! Lo tenemos todo... ¡comida deliciosa, bebidas fuertes, artefactos exóticos, lectura de la fortuna, premios increíbles y emociones sin fin! ¡No olvides canjear tus vales de la Feria de la Luna Negra con Gelvas Roñoso! Todo lo que pide son cinco o más y ya estarás recibiendo los premios más maravillosos de todo Terrallende. ¡Todo el mundo gana!' WHERE entry=2000005034;
UPDATE `db_script_string` SET `content_loc7`='¡Se escapa!' WHERE entry=2000005035;
UPDATE `db_script_string` SET `content_loc7`='¡Por favor! Debo alimentarme de algo pronto... Un cristal de maná... un fragmento... ¡Cualquier cosa! ¡El dolor es insoportable!' WHERE entry=2000005036;
UPDATE `db_script_string` SET `content_loc7`='Yo sólo podría ir a la caza de esa bestia miserable ahora que hay una recompensa por su cabeza.' WHERE entry=2000005037;
UPDATE `db_script_string` SET `content_loc7`='¡Dinos dónde se esconde tu líder!' WHERE entry=2000005038;
UPDATE `db_script_string` SET `content_loc7`='El viento nos habla de los movimientos de nuestros enemigos, Ashyen. Los Naga atacarán nuevamente.' WHERE entry=2000005039;
UPDATE `db_script_string` SET `content_loc7`='Muy bien. Cuando esa decisión se tome, estaré listo. Esperemos que no sea demasiado tarde.' WHERE entry=2000005040;
UPDATE `db_script_string` SET `content_loc7`='Haré mi mejor esfuerzo para cuidar de los niños, abuela.' WHERE entry=2000005041;
UPDATE `db_script_string` SET `content_loc7`='¡Una nueva publicación! Aventureros y héroes, ¡acérquense al cartel de anuncios!' WHERE entry=2000005042;
UPDATE `db_script_string` SET `content_loc7`='LO DESTRUIRE TODO' WHERE entry=2000005043;
UPDATE `db_script_string` SET `content_loc7`='TODOS NOSOTROS MAS Y MAS' WHERE entry=2000005044;
UPDATE `db_script_string` SET `content_loc7`='No me preguntes donde lo conseguí...' WHERE entry=2000005045;
UPDATE `db_script_string` SET `content_loc7`='Estoy buscando en esa recompensa después de este cambio.' WHERE entry=2000005046;
UPDATE `db_script_string` SET `content_loc7`='¿Quieres ir a pesar que la recompensa de este cartel de buscar se ha acabado después de este cambio?' WHERE entry=2000005047;
UPDATE `db_script_string` SET `content_loc7`='¿Tuvieron un buen día?' WHERE entry=2000005048;
UPDATE `db_script_string` SET `content_loc7`='Tengo otra lectura del interior.' WHERE entry=2000005049;
UPDATE `db_script_string` SET `content_loc7`='¡Bien, encárgate y vamos a ver lo que consigues!' WHERE entry=2000005050;
UPDATE `db_script_string` SET `content_loc7`='¡El Gran Gazlowe!' WHERE entry=2000005051;
UPDATE `db_script_string` SET `content_loc7`='Oye, tú. ¿Quieres un caramelo?' WHERE entry=2000005052;
UPDATE `db_script_string` SET `content_loc7`='¡Bip!' WHERE entry=2000005053;
UPDATE `db_script_string` SET `content_loc7`='¡Bip!' WHERE entry=2000005054;
UPDATE `db_script_string` SET `content_loc7`='¡Bip!' WHERE entry=2000005055;
UPDATE `db_script_string` SET `content_loc7`='Vale. Acabamos destrozando nuestras colas para transportar todas estas cosas aquí, ¿y quieres que trabajemos más?' WHERE entry=2000005056;
UPDATE `db_script_string` SET `content_loc7`='¡Llorica! ¡Llorica!' WHERE entry=2000005057;
UPDATE `db_script_string` SET `content_loc7`='¡La nena quiere su muñeca!' WHERE entry=2000005058;
UPDATE `db_script_string` SET `content_loc7`='¡Me pregunto si tu muñeca sabrá nadar!' WHERE entry=2000005059;
UPDATE `db_script_string` SET `content_loc7`='¡Ja, ja! ¡Tengo a Betsy!' WHERE entry=2000005060;
UPDATE `db_script_string` SET `content_loc7`='¡La nena quiere su muñeca!' WHERE entry=2000005061;
UPDATE `db_script_string` SET `content_loc7`='¡Tengo tu muñeca! ¡Chínchate!' WHERE entry=2000005062;
UPDATE `db_script_string` SET `content_loc7`='¡Llorica! ¡Llorica!' WHERE entry=2000005063;
UPDATE `db_script_string` SET `content_loc7`='¡La nena quiere su muñeca!' WHERE entry=2000005064;
UPDATE `db_script_string` SET `content_loc7`='¡Me pregunto si tu muñeca sabrá nadar!' WHERE entry=2000005065;
UPDATE `db_script_string` SET `content_loc7`='¡Ja, ja! ¡Tengo a Betsy!' WHERE entry=2000005066;
UPDATE `db_script_string` SET `content_loc7`='¡La nena quiere su muñeca!' WHERE entry=2000005067;
UPDATE `db_script_string` SET `content_loc7`='¡Tengo tu muñeca! ¡Chínchate!' WHERE entry=2000005068;
UPDATE `db_script_string` SET `content_loc7`='¡Llorica! ¡Llorica!' WHERE entry=2000005069;
UPDATE `db_script_string` SET `content_loc7`='¡La nena quiere su muñeca!' WHERE entry=2000005070;
UPDATE `db_script_string` SET `content_loc7`='¡Me pregunto si tu muñeca sabrá nadar!' WHERE entry=2000005071;
UPDATE `db_script_string` SET `content_loc7`='¡Ja, ja! ¡Tengo a Betsy!' WHERE entry=2000005072;
UPDATE `db_script_string` SET `content_loc7`='¡La nena quiere su muñeca!' WHERE entry=2000005073;
UPDATE `db_script_string` SET `content_loc7`='¡Tengo tu muñeca! ¡Chínchate!' WHERE entry=2000005074;
UPDATE `db_script_string` SET `content_loc7`='¡Llorica! ¡Llorica!' WHERE entry=2000005075;
UPDATE `db_script_string` SET `content_loc7`='¡La nena quiere su muñeca!' WHERE entry=2000005076;
UPDATE `db_script_string` SET `content_loc7`='¡Me pregunto si tu muñeca sabrá nadar!' WHERE entry=2000005077;
UPDATE `db_script_string` SET `content_loc7`='¡¡Dame mi muñeca!!' WHERE entry=2000005078;
UPDATE `db_script_string` SET `content_loc7`='¡¡Dame mi muñeca!!' WHERE entry=2000005079;
UPDATE `db_script_string` SET `content_loc7`='¡Basta! ¡Le vas a arrancar la cabeza!' WHERE entry=2000005080;
UPDATE `db_script_string` SET `content_loc7`='¡¡Dame mi muñeca!!' WHERE entry=2000005081;
UPDATE `db_script_string` SET `content_loc7`='¡¡Dame mi muñeca!!' WHERE entry=2000005082;
UPDATE `db_script_string` SET `content_loc7`='¡¡Dame mi muñeca!!' WHERE entry=2000005083;
UPDATE `db_script_string` SET `content_loc7`='¡¡Dame mi muñeca!!' WHERE entry=2000005084;
UPDATE `db_script_string` SET `content_loc7`='¡¡Dame mi muñeca!!' WHERE entry=2000005085;
UPDATE `db_script_string` SET `content_loc7`='¡Basta! ¡Le vas a arrancar la cabeza!' WHERE entry=2000005086;
UPDATE `db_script_string` SET `content_loc7`='¡¡Dame mi muñeca!!' WHERE entry=2000005087;
UPDATE `db_script_string` SET `content_loc7`='¡¡Dame mi muñeca!!' WHERE entry=2000005088;
UPDATE `db_script_string` SET `content_loc7`='¡¡Dame mi muñeca!!' WHERE entry=2000005089;
UPDATE `db_script_string` SET `content_loc7`='¡¡Dame mi muñeca!!' WHERE entry=2000005090;
UPDATE `db_script_string` SET `content_loc7`='¡¡Dame mi muñeca!!' WHERE entry=2000005091;
UPDATE `db_script_string` SET `content_loc7`='¡Basta! ¡Le vas a arrancar la cabeza!' WHERE entry=2000005092;
UPDATE `db_script_string` SET `content_loc7`='¡¡Dame mi muñeca!!' WHERE entry=2000005093;
UPDATE `db_script_string` SET `content_loc7`='¡¡Dame mi muñeca!!' WHERE entry=2000005094;
UPDATE `db_script_string` SET `content_loc7`='¡¡Dame mi muñeca!!' WHERE entry=2000005095;
UPDATE `db_script_string` SET `content_loc7`='¡¡Dame mi muñeca!!' WHERE entry=2000005096;
UPDATE `db_script_string` SET `content_loc7`='¡¡Dame mi muñeca!!' WHERE entry=2000005097;
UPDATE `db_script_string` SET `content_loc7`='¡Basta! ¡Le vas a arrancar la cabeza!' WHERE entry=2000005098;
UPDATE `db_script_string` SET `content_loc7`='¡Vendo pan recién horneado!' WHERE entry=2000005099;
UPDATE `db_script_string` SET `content_loc7`='Panecillos, bollos y pan de toda clase. ¡Pan recién horneado!' WHERE entry=2000005100;
UPDATE `db_script_string` SET `content_loc7`='¡Vendo pan recién horneado!' WHERE entry=2000005101;
UPDATE `db_script_string` SET `content_loc7`='Panecillos, bollos y pan de toda clase. ¡Pan recién horneado!' WHERE entry=2000005102;
UPDATE `db_script_string` SET `content_loc7`='¡Jack y Jill mis arrugados tesoritos! Yo hago todo el recorrido del agua por aquí.' WHERE entry=2000005103;
UPDATE `db_script_string` SET `content_loc7`='¿Dónde está el agua Emma? ¿Conseguiste el agua Emma? Si no fuera por mí ni sabría que apariencia tiene el agua.' WHERE entry=2000005104;
UPDATE `db_script_string` SET `content_loc7`='Por supuesto que hablo conmigo misma. Es la única manera de conseguir una conversación decente en esta ciudad.' WHERE entry=2000005105;
UPDATE `db_script_string` SET `content_loc7`='Como si no tuviera mejores cosas que hacer en mi vejez, que llevar cubos de agua.' WHERE entry=2000005106;
UPDATE `db_script_string` SET `content_loc7`='Parece que fueran cien veces al día que recorro este camino por más agua. No respetan a sus mayores. Lo digo yo.' WHERE entry=2000005107;
UPDATE `db_script_string` SET `content_loc7`='Deja vú. Por un momento pensé que había vuelto a casa... antes que la Plaga...' WHERE entry=2000005108;
UPDATE `db_script_string` SET `content_loc7`='Dicen que él puede a veces transformarse en cuervo.' WHERE entry=2000005109;
UPDATE `db_script_string` SET `content_loc7`='Y dicen que él puede a veces convertirse en cuervo.' WHERE entry=2000005110;
UPDATE `db_script_string` SET `content_loc7`='Y entonces el conejo así mordió su cabeza... Lo juro.' WHERE entry=2000005111;
UPDATE `db_script_string` SET `content_loc7`='Lo juro, hay personas que lo han visto. ¡¡Pandaren realmente sí existe!!' WHERE entry=2000005112;
UPDATE `db_script_string` SET `content_loc7`='¿Sabes por qué los ojos de los Orcos brillan con color rojo? ¡Porque ellos beben sangre!' WHERE entry=2000005113;
UPDATE `db_script_string` SET `content_loc7`='No creo que haya peces en estos canales.' WHERE entry=2000005114;
UPDATE `db_script_string` SET `content_loc7`='¡Y así es como Lother mató a treinta y seis orcos con sus propias manos!' WHERE entry=2000005115;
UPDATE `db_script_string` SET `content_loc7`='Oye... ¡esto no es un pez!' WHERE entry=2000005116;
UPDATE `db_script_string` SET `content_loc7`='Conseguí intestinos de gusano en mis zapatos.' WHERE entry=2000005117;
UPDATE `db_script_string` SET `content_loc7`='Creo que veo algo.' WHERE entry=2000005118;
UPDATE `db_script_string` SET `content_loc7`='Oye... ¡esto no es un pez!' WHERE entry=2000005119;
UPDATE `db_script_string` SET `content_loc7`='Creo que veo algo.' WHERE entry=2000005120;
UPDATE `db_script_string` SET `content_loc7`='¡Espero que esto sea un pez!' WHERE entry=2000005121;
UPDATE `db_script_string` SET `content_loc7`='El gusano va en el anzuelo, el anzuelo entra al agua, el Pez está en el agua, nuestro pez.' WHERE entry=2000005122;
UPDATE `db_script_string` SET `content_loc7`='¿Puedes imaginarlo?' WHERE entry=2000005123;
UPDATE `db_script_string` SET `content_loc7`='¿De veras?' WHERE entry=2000005124;
UPDATE `db_script_string` SET `content_loc7`='Vaya.' WHERE entry=2000005125;
UPDATE `db_script_string` SET `content_loc7`='Mi padre dice que esa es sólo una historia.' WHERE entry=2000005126;
UPDATE `db_script_string` SET `content_loc7`='¿De veras?' WHERE entry=2000005127;
UPDATE `db_script_string` SET `content_loc7`='Vaya.' WHERE entry=2000005128;
UPDATE `db_script_string` SET `content_loc7`='Eso está limpio.' WHERE entry=2000005129;
UPDATE `db_script_string` SET `content_loc7`='Vaya.' WHERE entry=2000005130;
UPDATE `db_script_string` SET `content_loc7`='¿De veras?' WHERE entry=2000005131;
UPDATE `db_script_string` SET `content_loc7`='¡Parecen estar vivos, perros! ¡Tenemos una operación que realizar aquí!' WHERE entry=2000005132;
UPDATE `db_script_string` SET `content_loc7`='¿Tuvieron un buen día?' WHERE entry=2000005133;
UPDATE `db_script_string` SET `content_loc7`='Aquí tenemos la Catedral de la Luz, el centro de la iluminación espiritual aquí en Ventormenta.' WHERE entry=2000005134;
UPDATE `db_script_string` SET `content_loc7`='Sí, es verdad. Los paladines y sacerdotes por igual entrenan sus habilidades y estudian grandes verdades  tras los muros de la Catedral.' WHERE entry=2000005135;
UPDATE `db_script_string` SET `content_loc7`='Niños si hacen el favor de seguirme, ahora iremos a ver la fortaleza donde el Rey Varian Wrynn se sienta sobre su trono.' WHERE entry=2000005136;
UPDATE `db_script_string` SET `content_loc7`='Aquí tenemos la Fortaleza de Ventormenta. Construida sobre las ruinas del Castillo de Ventormenta, que fué destruida por la Horda en la primera Gran Guerra.' WHERE entry=2000005137;
UPDATE `db_script_string` SET `content_loc7`='Cuando la Horda fue derrotada, los hombres regresaron aquí y comenzaron a reconstruir lo que una vez fué una gran ciudad como testimonio de nuestra propia supervivencia.' WHERE entry=2000005138;
UPDATE `db_script_string` SET `content_loc7`='Sí, bueno... ahora vamos al monumento dedicado a los héroes de las dos Grandes Guerras, el Valle de los Héroes. Síganme.' WHERE entry=2000005139;
UPDATE `db_script_string` SET `content_loc7`='¿No es asombroso, niños? Todo el que entra a la ciudad debe caminar bajo los ojos vigilantes de los más grandes héroes de nuestras tierras.' WHERE entry=2000005140;
UPDATE `db_script_string` SET `content_loc7`='Quita el aliento. Niños, cuando regresemos a la escuela, cada uno dará un informe oral sobre uno de estos personajes legendarios.' WHERE entry=2000005141;
UPDATE `db_script_string` SET `content_loc7`='Ahora, echen otra mirada antes de que regresemos al Santo Distrito y a la gran Catedral de la Luz.' WHERE entry=2000005142;
UPDATE `db_script_string` SET `content_loc7`='Esto nunca sucedió...' WHERE entry=2000005143;
UPDATE `db_script_string` SET `content_loc7`='¡Esto debe arreglarse!' WHERE entry=2000005144;
UPDATE `db_script_string` SET `content_loc7`='¿¡Cómo puede alguien vivir así!?' WHERE entry=2000005145;
UPDATE `db_script_string` SET `content_loc7`='¡Pato!' WHERE entry=2000005146;
UPDATE `db_script_string` SET `content_loc7`='¡No vayas cerca del lago! ¡está encantada!' WHERE entry=2000005147;
UPDATE `db_script_string` SET `content_loc7`='Poner doce centros de enfoque podría permitir energías mágicas de forma más sólidas, agregando la estabilidad necesaria.' WHERE entry=2000005148;
UPDATE `db_script_string` SET `content_loc7`='Por lo menos no estaríamos cerca de tener que limpiarlo.' WHERE entry=2000005149;
UPDATE `db_script_string` SET `content_loc7`='Sólo si no siguió los procedimientos de inicialización adecuada.' WHERE entry=2000005150;
UPDATE `db_script_string` SET `content_loc7`='Sin embargo, las energías resultantes podrían colapsar, y podrían causar un flujo de energía que te darían un ataque de migraña durante semanas.' WHERE entry=2000005151;
UPDATE `db_script_string` SET `content_loc7`='Sólo si no siguió los procedimientos de inicialización adecuada.' WHERE entry=2000005152;
UPDATE `db_script_string` SET `content_loc7`='Sólo si no siguió los procedimientos de inicialización adecuada.' WHERE entry=2000005153;
UPDATE `db_script_string` SET `content_loc7`='Por lo menos no estaríamos cerca de tener que limpiarlo.' WHERE entry=2000005154;
UPDATE `db_script_string` SET `content_loc7`='¿Pero no fue eso lo que causó los problemas iniciales con la fórmula mágica de la Adepta Syleria?' WHERE entry=2000005155;
UPDATE `db_script_string` SET `content_loc7`='Supongo que podría funcionar, si tuviéramos veinte personas con quienes probarlo.' WHERE entry=2000005156;
UPDATE `db_script_string` SET `content_loc7`='Pero, ¿y si el cambio de la frecuencia resultantes fueron para enviar reacciones mágicas hacia los flujos?' WHERE entry=2000005157;
UPDATE `db_script_string` SET `content_loc7`='Cuando chocan las energías positivas alineadas con las energías de carga negativa, se neutralizan entre sí.' WHERE entry=2000005158;
UPDATE `db_script_string` SET `content_loc7`='Sin embargo, esto generaría un desequilibrio en el centro mágico y causaría una vibración inversa en el éter.' WHERE entry=2000005159;
UPDATE `db_script_string` SET `content_loc7`='¿Pero no significaría eso un cruce de corrientes? ¿sería realmente malo?' WHERE entry=2000005160;
UPDATE `db_script_string` SET `content_loc7`='¿Por qué no podemos simplemente cambiar el orden para compensar la variación del flujo?' WHERE entry=2000005161;
UPDATE `db_script_string` SET `content_loc7`='¿Pero no fue eso lo que causó los problemas iniciales con la fórmula mágica de la Adepta Syleria?' WHERE entry=2000005162;
UPDATE `db_script_string` SET `content_loc7`='Pienso que no, no necesito estallar de nuevo.' WHERE entry=2000005163;
UPDATE `db_script_string` SET `content_loc7`='Maginor dice que torcer las corrientes alternas de energía positiva en realidad crea un flujo mucho más estable.' WHERE entry=2000005164;
UPDATE `db_script_string` SET `content_loc7`='¿Pero no significaría eso un cruce de corrientes? ¿sería realmente malo?' WHERE entry=2000005165;
UPDATE `db_script_string` SET `content_loc7`='¿Pero no fue eso lo que causó los problemas iniciales con la fórmula mágica de la Adepta Syleria?' WHERE entry=2000005166;
UPDATE `db_script_string` SET `content_loc7`='¿Es verdad que los paladines entrenan aquí?' WHERE entry=2000005167;
UPDATE `db_script_string` SET `content_loc7`='¿Por qué tenemos que aprender esta materia de todos modos?' WHERE entry=2000005168;
UPDATE `db_script_string` SET `content_loc7`='Si revertimos el flujo de la Esencia quizás podamos alterar la polaridad.' WHERE entry=2000005169;
UPDATE `db_script_string` SET `content_loc7`='¿Qué pasaría si utilizásemos tres focos de acuerdo con el patrón tireano? Eso lo resolvería.' WHERE entry=2000005170;
UPDATE `db_script_string` SET `content_loc7`='Vaya, todo esto por una poción de amor. Espero que él lo valga.' WHERE entry=2000005171;
UPDATE `db_script_string` SET `content_loc7`='Si utilizamos la secuencia apropiada debería estar bien. Sólo tomaría algún estudio serio antes de empezar.' WHERE entry=2000005172;
UPDATE `db_script_string` SET `content_loc7`='El Portal se desplazará ligeramente. En ese momento, si lanzas una poción vinculante lo solidificarías en su lugar.' WHERE entry=2000005173;
UPDATE `db_script_string` SET `content_loc7`='Vaya, todo esto por una poción de amor. Espero que él lo valga.' WHERE entry=2000005174;
UPDATE `db_script_string` SET `content_loc7`='Pero si lo estabilizamos con un hilo de ancla en el nudo energético apropiado, tendría que funcionar.' WHERE entry=2000005175;
UPDATE `db_script_string` SET `content_loc7`='¿Qué pasaría si utilizásemos tres focos de acuerdo con el patrón tireano? Eso lo resolvería.' WHERE entry=2000005176;
UPDATE `db_script_string` SET `content_loc7`='Si utilizamos la secuencia apropiada debería estar bien. Sólo tomaría algún estudio serio antes de empezar.' WHERE entry=2000005177;
UPDATE `db_script_string` SET `content_loc7`='Pero si lo estabilizamos con un hilo de ancla en el nudo energético apropiado, tendría que funcionar.' WHERE entry=2000005178;
UPDATE `db_script_string` SET `content_loc7`='Vaya, todo esto por una poción de amor. Espero que él lo valga.' WHERE entry=2000005179;
UPDATE `db_script_string` SET `content_loc7`='Hola, Charys. Tengo mi lista, ¿podrías hacerme todo esto? Sobretodo el último ingrediente.' WHERE entry=2000005180;
UPDATE `db_script_string` SET `content_loc7`='Claro Paige. Será un placer.' WHERE entry=2000005181;
UPDATE `db_script_string` SET `content_loc7`='Gracias, Charys. Vamos Paige, cariño.' WHERE entry=2000005182;
UPDATE `db_script_string` SET `content_loc7`='Mamá, ¿Puedo quedarme con Esfumador?' WHERE entry=2000005183;
UPDATE `db_script_string` SET `content_loc7`='Esfumador era un gran mago. Pero se convirtió en un conejo cuando uno de sus hechizos salió mal.' WHERE entry=2000005184;
UPDATE `db_script_string` SET `content_loc7`='¿Tus estudios de magia te estresan? ¡Relájate en el Ermitaño Azul!' WHERE entry=2000005185;
UPDATE `db_script_string` SET `content_loc7`='¡Las mejores bebidas de Ventormenta!' WHERE entry=2000005186;
UPDATE `db_script_string` SET `content_loc7`='Ven al Ermitaño Azul. ¡Donde todo el mundo sabe tu nombre!' WHERE entry=2000005187;
UPDATE `db_script_string` SET `content_loc7`='¿Te sientes triste? ¡Vamos al Ermitaño Azul a pasar un buen rato!' WHERE entry=2000005188;
UPDATE `db_script_string` SET `content_loc7`='¡Las mejores bebidas de Ventormenta!' WHERE entry=2000005189;
UPDATE `db_script_string` SET `content_loc7`='¿Tus estudios de magia te estresan? ¡Relájate en el Ermitaño Azul!' WHERE entry=2000005190;
UPDATE `db_script_string` SET `content_loc7`='¡Pregúntame cómo conseguir una bebida gratis en El Ermitaño Azul!' WHERE entry=2000005191;
UPDATE `db_script_string` SET `content_loc7`='Ven al Ermitaño Azul. ¡Donde todo el mundo sabe tu nombre!' WHERE entry=2000005192;
UPDATE `db_script_string` SET `content_loc7`='¡Bebidas gratis en El Ermitaño Azul!' WHERE entry=2000005193;
UPDATE `db_script_string` SET `content_loc7`='¿Te sientes triste? ¡Vamos al Ermitaño Azul a pasar un buen rato!' WHERE entry=2000005194;
UPDATE `db_script_string` SET `content_loc7`='¿Tus estudios de magia te estresan? ¡Relájate en el Ermitaño Azul!' WHERE entry=2000005195;
UPDATE `db_script_string` SET `content_loc7`='¡Las mejores bebidas de Ventormenta!' WHERE entry=2000005196;
UPDATE `db_script_string` SET `content_loc7`='¡Pregúntame cómo conseguir una bebida gratis en El Ermitaño Azul!' WHERE entry=2000005197;
UPDATE `db_script_string` SET `content_loc7`='Ven al Ermitaño Azul. ¡Donde todo el mundo sabe tu nombre!' WHERE entry=2000005198;
UPDATE `db_script_string` SET `content_loc7`='¡Las mejores bebidas de Ventormenta!' WHERE entry=2000005199;
UPDATE `db_script_string` SET `content_loc7`='¡A la carga!' WHERE entry=2000005200;
UPDATE `db_script_string` SET `content_loc7`='¡A la carga!' WHERE entry=2000005201;
UPDATE `db_script_string` SET `content_loc7`='Ah, ¡mi preciosa Ameenah! Qué maravilloso volver a verte.' WHERE entry=2000005202;
UPDATE `db_script_string` SET `content_loc7`='Te estás agotando, princesa, ¡puedo sentirlo!' WHERE entry=2000005203;
UPDATE `db_script_string` SET `content_loc7`='Mmm, ¡No les importa si lo hago!' WHERE entry=2000005204;
UPDATE `db_script_string` SET `content_loc7`='Ya viene, Papasfritas. ¿No tienes una demostración del producto que hacer o algo así?' WHERE entry=2000005205;
UPDATE `db_script_string` SET `content_loc7`='¡Sé el primero de tu vecindario en poseer el increíble Lanzador de maculación electrostática!' WHERE entry=2000005206;
UPDATE `db_script_string` SET `content_loc7`='Derivado de la tecnología militar de vanguardia de la Ofensiva Mano Devastada, ¡quita manchas dificiles de sacar!' WHERE entry=2000005207;
UPDATE `db_script_string` SET `content_loc7`='¡Manchas de vino, manchas de césped, aún manchas de mascotas no son rivales para el Lanzador de maculación electrostática!' WHERE entry=2000005208;
UPDATE `db_script_string` SET `content_loc7`='¡No espere más! Haga ahora su pedido y recibirá mis papas ultra-cinéticas de hierro sin cargo adicional!' WHERE entry=2000005209;
UPDATE `db_script_string` SET `content_loc7`='No me detendré. Nunca...' WHERE entry=2000005210;
UPDATE `db_script_string` SET `content_loc7`='Estas llamas han permanecido ardiendo constantemente por años. Insólita dedicación de los trols.' WHERE entry=2000005237;
UPDATE `db_script_string` SET `content_loc7`='Extraño... Estos mosaicos no se parece a ninguna tradición conocida de los trol.' WHERE entry=2000005238;
UPDATE `db_script_string` SET `content_loc7`='Sí, sí, Estoy bastante seguro de que esto representa la fusión de entidades. Fascinante.' WHERE entry=2000005239;
UPDATE `db_script_string` SET `content_loc7`='Uno puede aprender mucho de una cultura mediante el estudio de su basura.' WHERE entry=2000005240;
UPDATE `db_script_string` SET `content_loc7`='Uh. Manojos de cabello enredado, plumas mudadas, trozos de hueso, material parcialmente quemado... ¿quizás prendas de vestir?' WHERE entry=2000005241;
UPDATE `db_script_string` SET `content_loc7`='En realidad, deberíamos reparar la cerca pronto.' WHERE entry=2000005400;
UPDATE `db_script_string` SET `content_loc7`='<suspirando> Es hora de comprobar en el cementerio de nuevo... Volveré en pocos minutos.' WHERE entry=2000005401;
UPDATE `db_script_string` SET `content_loc7`='¿Cuánto tiempo puede tomar recoger un puñado de hierbas?' WHERE entry=2000005402;
UPDATE `db_script_string` SET `content_loc7`='¡A este ritmo podría reunirlas por mí mismo!' WHERE entry=2000005403;
UPDATE `db_script_string` SET `content_loc7`='Ah, este debe ser él ahora... ¿no? ¡bah!' WHERE entry=2000005404;
UPDATE `db_script_string` SET `content_loc7`='Como si yo tuviera toda la eternidad.' WHERE entry=2000005405;
UPDATE `db_script_string` SET `content_loc7`='¡Estamos agotando el hierro, muchachos! No quiero ver ni una sola barra echarse a perder, ¿me oyen?' WHERE entry=2000005406;
UPDATE `db_script_string` SET `content_loc7`='No está mal. Intenta el truco del que te hablé sobre templar el acero.' WHERE entry=2000005407;
UPDATE `db_script_string` SET `content_loc7`='Albañiles... arrg... Defias estar advertidos:  El ancla oxidada se hundirá esta noche' WHERE entry=2000005408;
UPDATE `db_script_string` SET `content_loc7`='¡%s invoca a los poderosos ejércitos de la Plaga!' WHERE entry=2000005409;
UPDATE `db_script_string` SET `content_loc7`='¡Ejércitos de la Plaga, escuchad mi llamada! ¡El apocalipsis escarlata ha comenzado! ¡Destrozad esta tierra y no dejéis más que muerte a vuestro paso!' WHERE entry=2000005410;
