-- ================== --
--   TRINITY_STRING   --
--       --
-- ================== --

UPDATE trinity_string SET `content_loc7`='Debes seleccionar un personaje o criatura.' WHERE entry=1;
UPDATE trinity_string SET `content_loc7`='Debes seleccionar una criatura.' WHERE entry=2;
UPDATE trinity_string SET `content_loc7`='[SERVIDOR] %s' WHERE entry=3;
UPDATE trinity_string SET `content_loc7`='|cffff0000[Mensaje de Evento]: %s|r' WHERE entry=4;
UPDATE trinity_string SET `content_loc7`='No hay ayuda para ese comando.' WHERE entry=5;
UPDATE trinity_string SET `content_loc7`='No existe ese comando' WHERE entry=6;
UPDATE trinity_string SET `content_loc7`='No existe ese subcomando' WHERE entry=7;
UPDATE trinity_string SET `content_loc7`='El comando %s tiene subcomandos: %s' WHERE entry=8;
UPDATE trinity_string SET `content_loc7`='Comandos disponibles: ' WHERE entry=9;
UPDATE trinity_string SET `content_loc7`='Sintaxis incorrecta.' WHERE entry=10;
UPDATE trinity_string SET `content_loc7`='Tu nivel de cuenta es: %i' WHERE entry=11;
UPDATE trinity_string SET `content_loc7`='Jugadores conectados: %u (max: %u) Jugadores en espera: %u (max: %u)' WHERE entry=12;
UPDATE trinity_string SET `content_loc7`='Servidor en línea: %s' WHERE entry=13;
UPDATE trinity_string SET `content_loc7`='Jugador guardado.' WHERE entry=14;
UPDATE trinity_string SET `content_loc7`='Todos los jugadores guardados.' WHERE entry=15;
UPDATE trinity_string SET `content_loc7`='Estos son los MJs activos en el servidor:' WHERE entry=16;
UPDATE trinity_string SET `content_loc7`='En este momento no hay ningun MJ conectado en el servidor.' WHERE entry=17;
UPDATE trinity_string SET `content_loc7`='No puedes hacer eso volando.' WHERE entry=18;
UPDATE trinity_string SET `content_loc7`='No puedes hacer eso en Campos de Batalla.' WHERE entry=19;
UPDATE trinity_string SET `content_loc7`='El objetivo está volando y no puede hacer eso.' WHERE entry=20;
UPDATE trinity_string SET `content_loc7`='%s está volando y el comando queda invalidado.' WHERE entry=21;
UPDATE trinity_string SET `content_loc7`='No estas montando así que no puedes desmontar.' WHERE entry=22;
UPDATE trinity_string SET `content_loc7`='No puedes hacer eso luchando.' WHERE entry=23;
UPDATE trinity_string SET `content_loc7`='Ya lo usaste recientemente.' WHERE entry=24;
UPDATE trinity_string SET `content_loc7`='¡No se cambió la contraseña (error desconocido)!' WHERE entry=25;
UPDATE trinity_string SET `content_loc7`='La contraseña ha sido cambiada' WHERE entry=26;
UPDATE trinity_string SET `content_loc7`='La contraseña anterior es incorrecta.' WHERE entry=27;
UPDATE trinity_string SET `content_loc7`='Tu cuenta ahora está bloqueada.' WHERE entry=28;
UPDATE trinity_string SET `content_loc7`='Tu cuenta ahora está desbloqueada.' WHERE entry=29;
UPDATE trinity_string SET `content_loc7`=', rango ' WHERE entry=30;
UPDATE trinity_string SET `content_loc7`=' [conocido]' WHERE entry=31;
UPDATE trinity_string SET `content_loc7`=' [aprender]' WHERE entry=32;
UPDATE trinity_string SET `content_loc7`=' [pasivo]' WHERE entry=33;
UPDATE trinity_string SET `content_loc7`=' [talento]' WHERE entry=34;
UPDATE trinity_string SET `content_loc7`=' [activo]' WHERE entry=35;
UPDATE trinity_string SET `content_loc7`=' [completo]' WHERE entry=36;
UPDATE trinity_string SET `content_loc7`=' (desconectado)' WHERE entry=37;
UPDATE trinity_string SET `content_loc7`='activado' WHERE entry=38;
UPDATE trinity_string SET `content_loc7`='desactivado' WHERE entry=39;
UPDATE trinity_string SET `content_loc7`='Tu eres: %s' WHERE entry=40;
UPDATE trinity_string SET `content_loc7`='visible' WHERE entry=41;
UPDATE trinity_string SET `content_loc7`='invisible' WHERE entry=42;
UPDATE trinity_string SET `content_loc7`='hecho' WHERE entry=43;
UPDATE trinity_string SET `content_loc7`='Tu' WHERE entry=44;
UPDATE trinity_string SET `content_loc7`=' <desconocido> ' WHERE entry=45;
UPDATE trinity_string SET `content_loc7`='<error>' WHERE entry=46;
UPDATE trinity_string SET `content_loc7`='<personaje inexistente>' WHERE entry=47;
UPDATE trinity_string SET `content_loc7`='DESCONOCIDO' WHERE entry=48;
UPDATE trinity_string SET `content_loc7`='Debes ser como mínimo nivel %u para entrar.' WHERE entry=49;
UPDATE trinity_string SET `content_loc7`='Debes ser como mínimo nivel %u y tener el objeto %s para entrar.' WHERE entry=50;
UPDATE trinity_string SET `content_loc7`='¡Hola! ¿Preparado para el entrenamiento?' WHERE entry=51;
UPDATE trinity_string SET `content_loc7`='Contador de objeto no válido (%u) para el objeto %u' WHERE entry=52;
UPDATE trinity_string SET `content_loc7`='El correo no puede tener más de %u objetos adjuntos' WHERE entry=53;
UPDATE trinity_string SET `content_loc7`='Las nuevas contraseñas no coinciden' WHERE entry=54;
UPDATE trinity_string SET `content_loc7`='¡La contraseña no puede ser más larga de 16 caracteres (el límite del cliente), la contraseña no se ha cambiado!' WHERE entry=55;
UPDATE trinity_string SET `content_loc7`='Mensaje del día: \r\n%s' WHERE entry=56;
UPDATE trinity_string SET `content_loc7`='Usando BD para el mundo: %s' WHERE entry=57;
UPDATE trinity_string SET `content_loc7`='Usando libreria de scripts: %s' WHERE entry=58;
UPDATE trinity_string SET `content_loc7`='Usando EventAI de criaturas: %s' WHERE entry=59;
UPDATE trinity_string SET `content_loc7`='Jugadores conectados: %u (max: %u)' WHERE entry=60;
UPDATE trinity_string SET `content_loc7`='Expansión %u ahora activada.' WHERE entry=61;
UPDATE trinity_string SET `content_loc7`='Uno o más parámetros tienen valores incorrectos' WHERE entry=62;
UPDATE trinity_string SET `content_loc7`='Objetivo no válido' WHERE entry=63;
UPDATE trinity_string SET `content_loc7`='No puedes usar ese objeto aquí.' WHERE entry=64;
UPDATE trinity_string SET `content_loc7`='Debes alcanzar el nivel 58 para usar este portal.' WHERE entry=65;
UPDATE trinity_string SET `content_loc7`='Notificación Global: ' WHERE entry=100;
UPDATE trinity_string SET `content_loc7`='Mapa: %u (%s) Zona: %u (%s) Área: %u (%s) Fase: %u\nX: %f Y: %f Z: %f Orientación: %f\ngrid[%u,%u]cell[%u,%u] IDMazmorra: %u\n ZoneX: %f ZoneY: %f\nGroundZ: %f FloorZ: %f Tiene datos de altura (Map: %u VMap: %u)' WHERE entry=101;
UPDATE trinity_string SET `content_loc7`='%s ya está siendo teletransportado.' WHERE entry=102;
UPDATE trinity_string SET `content_loc7`='Puedes invocar a un jugador a la mazmorra sólo si tienes el liderazgo del grupo.' WHERE entry=103;
UPDATE trinity_string SET `content_loc7`='No puedes ir a la mazmorra del jugador, porque ya estás en un grupo.' WHERE entry=104;
UPDATE trinity_string SET `content_loc7`='Puedes ir a la mazmorra de ese jugador mientras no seas de su grupo sólamente si el modo MJ está activado.' WHERE entry=105;
UPDATE trinity_string SET `content_loc7`='No puedes ir hasta el jugador %s de mazmorra a mazmorra.' WHERE entry=106;
UPDATE trinity_string SET `content_loc7`='No puedes invocar al jugador %s de mazmorra a mazmorra.' WHERE entry=107;
UPDATE trinity_string SET `content_loc7`='Estás invocando a %s%s.' WHERE entry=108;
UPDATE trinity_string SET `content_loc7`='Has sido invocado por %s.' WHERE entry=109;
UPDATE trinity_string SET `content_loc7`='Estás teletransportando a %s%s hacia %s.' WHERE entry=110;
UPDATE trinity_string SET `content_loc7`='Estás siendo teletransportado por %s.' WHERE entry=111;
UPDATE trinity_string SET `content_loc7`='El jugador (%s) no existe.' WHERE entry=112;
UPDATE trinity_string SET `content_loc7`='Apareciendo en la posición de %s' WHERE entry=113;
UPDATE trinity_string SET `content_loc7`='%s está apareciendo en tu posición.' WHERE entry=114;
UPDATE trinity_string SET `content_loc7`='Valores incorrectos' WHERE entry=115;
UPDATE trinity_string SET `content_loc7`='No has seleccionado ningún personaje.' WHERE entry=116;
UPDATE trinity_string SET `content_loc7`='%s no está en un grupo' WHERE entry=117;
UPDATE trinity_string SET `content_loc7`='Cambiaste la VIDA de %s a %i/%i.' WHERE entry=118;
UPDATE trinity_string SET `content_loc7`='%s cambió tu VIDA a %i/%i.' WHERE entry=119;
UPDATE trinity_string SET `content_loc7`='Cambiaste el MANÁ de %s a %i/%i.' WHERE entry=120;
UPDATE trinity_string SET `content_loc7`='%s cambió tu MANÁ a %i/%i.' WHERE entry=121;
UPDATE trinity_string SET `content_loc7`='Cambiaste la ENERGÍA de %s a %i/%i.' WHERE entry=122;
UPDATE trinity_string SET `content_loc7`='%s cambió tu ENERGÍA a %i/%i.' WHERE entry=123;
UPDATE trinity_string SET `content_loc7`='Energía actual: %u' WHERE entry=124;
UPDATE trinity_string SET `content_loc7`='Cambiaste la ira de %s a %i/%i.' WHERE entry=125;
UPDATE trinity_string SET `content_loc7`='%s cambió tu ira a %i/%i.' WHERE entry=126;
UPDATE trinity_string SET `content_loc7`='Cambiaste el nivel de %s a %i.' WHERE entry=127;
UPDATE trinity_string SET `content_loc7`='GUID %i, facción es %i, flags es %i, npcflag es %i, DY flag es %i' WHERE entry=128;
UPDATE trinity_string SET `content_loc7`='Facción incorrecta: %u (No se encontró en factiontemplate.dbc)' WHERE entry=129;
UPDATE trinity_string SET `content_loc7`='Has cambiado GUID=%i Facción a %i, flags a %i, npcflag a %i, dyflag a %i.' WHERE entry=130;
UPDATE trinity_string SET `content_loc7`='Has cambiado los spellflatid=%i, val= %i, mark =%i a %s.' WHERE entry=131;
UPDATE trinity_string SET `content_loc7`='%s cambió tus spellflatid=%i, val= %i, mark =%i.' WHERE entry=132;
UPDATE trinity_string SET `content_loc7`='Ahora %s tiene acceso a todas las rutas de vuelo (hasta el cierre de sesión)' WHERE entry=133;
UPDATE trinity_string SET `content_loc7`='Ahora %s ya no tiene acceso a todas las rutas de vuelo (sólo acceso de visitante)' WHERE entry=134;
UPDATE trinity_string SET `content_loc7`='%s te ha dado acceso a todas las rutas de vuelo (hasta el cierre de sesión).' WHERE entry=135;
UPDATE trinity_string SET `content_loc7`='%s te ha retirado el acceso a todas las rutas de vuelo (sólo acceso de visitante).' WHERE entry=136;
UPDATE trinity_string SET `content_loc7`='Has cambiado todas las velocidades a %2.2f veces la normal de %s.' WHERE entry=137;
UPDATE trinity_string SET `content_loc7`='%s cambió todas las velocidades a %2.2f veces la normal.' WHERE entry=138;
UPDATE trinity_string SET `content_loc7`='Has cambiado la velocidad a %2.2f veces la normal de %s.' WHERE entry=139;
UPDATE trinity_string SET `content_loc7`='%s cambió tu velocidad a %2.2f veces la normal.' WHERE entry=140;
UPDATE trinity_string SET `content_loc7`='Has cambiado la velocidad de nado a %2.2f veces la normal de %s.' WHERE entry=141;
UPDATE trinity_string SET `content_loc7`='%s cambió tu velocidad de nado a %2.2f veces la normal.' WHERE entry=142;
UPDATE trinity_string SET `content_loc7`='Has cambiado la velocidad hacia atrás a %2.2f veces la normal de %s.' WHERE entry=143;
UPDATE trinity_string SET `content_loc7`='%s cambió tu velocidad hacia atrás a %2.2f veces la normal.' WHERE entry=144;
UPDATE trinity_string SET `content_loc7`='Has cambiado la velocidad de vuelo a %2.2f veces la normal de %s.' WHERE entry=145;
UPDATE trinity_string SET `content_loc7`='%s cambió tu velocidad de vuelo a %2.2f veces la normal.' WHERE entry=146;
UPDATE trinity_string SET `content_loc7`='Has cambiado el tamaño a %2.2f de %s.' WHERE entry=147;
UPDATE trinity_string SET `content_loc7`='%s cambió tu tamaño a %2.2f.' WHERE entry=148;
UPDATE trinity_string SET `content_loc7`='No hay ninguna montura.' WHERE entry=149;
UPDATE trinity_string SET `content_loc7`='Das una montura a %s.' WHERE entry=150;
UPDATE trinity_string SET `content_loc7`='%s te entregó una montura.' WHERE entry=151;
UPDATE trinity_string SET `content_loc7`='USUARIO1: %i, AÑAD: %i, DIF: %i\n' WHERE entry=152;
UPDATE trinity_string SET `content_loc7`='Tomas todas las monedas de cobre de %s.' WHERE entry=153;
UPDATE trinity_string SET `content_loc7`='%s tomó todo tu cobre.' WHERE entry=154;
UPDATE trinity_string SET `content_loc7`='Tomaste %i monedas de cobre de %s.' WHERE entry=155;
UPDATE trinity_string SET `content_loc7`='%s toma %i monedas de cobre de ti.' WHERE entry=156;
UPDATE trinity_string SET `content_loc7`='Entregas %i monedas de cobre a %s.' WHERE entry=157;
UPDATE trinity_string SET `content_loc7`='%s te entrega %i monedas de cobre.' WHERE entry=158;
UPDATE trinity_string SET `content_loc7`='Escuchas el sonido %u.' WHERE entry=159;
UPDATE trinity_string SET `content_loc7`='USUARIO2: %i, AÑAD: %i, RESULT: %i\n' WHERE entry=160;
UPDATE trinity_string SET `content_loc7`='Eliminado bit %i en campo %i.' WHERE entry=161;
UPDATE trinity_string SET `content_loc7`='Insertado bit %i en campo %i.' WHERE entry=162;
UPDATE trinity_string SET `content_loc7`='¡La tabla de ubicación de teletransporte esta vacía!' WHERE entry=163;
UPDATE trinity_string SET `content_loc7`='¡Ubicación de teletransporte no encontrada!' WHERE entry=164;
UPDATE trinity_string SET `content_loc7`='Requiere parametro de búsqueda.' WHERE entry=165;
UPDATE trinity_string SET `content_loc7`='No hay ninguna posición de teletransporte que coincida con tu petición.' WHERE entry=166;
UPDATE trinity_string SET `content_loc7`='Las ubicaciones encontradas son:\n%s' WHERE entry=168;
UPDATE trinity_string SET `content_loc7`='Correo enviado a %s' WHERE entry=169;
UPDATE trinity_string SET `content_loc7`='Intentas oir el sonido %u, pero no existe.' WHERE entry=170;
UPDATE trinity_string SET `content_loc7`='¡No puedes teletransportarte hacia ti mismo!' WHERE entry=171;
UPDATE trinity_string SET `content_loc7`='comando de consola del servidor' WHERE entry=172;
UPDATE trinity_string SET `content_loc7`='Has cambiado el poder rúnico de %s a %i/%i.' WHERE entry=173;
UPDATE trinity_string SET `content_loc7`='%s cambió tu poder rúnico a %i/%i.' WHERE entry=174;
UPDATE trinity_string SET `content_loc7`='Nivel de líquido: %f, tierra: %f, tipo: %d, estado: %d' WHERE entry=175;
UPDATE trinity_string SET `content_loc7`='Nada seleccionado.' WHERE entry=200;
UPDATE trinity_string SET `content_loc7`='El GUID del objeto es: parte baja %u parte alta %X' WHERE entry=201;
UPDATE trinity_string SET `content_loc7`='El nombre es demasiado largo, sobran %i caracteres.' WHERE entry=202;
UPDATE trinity_string SET `content_loc7`='Error, el nombre sólo puede contener caracteres A-Z y a-z.' WHERE entry=203;
UPDATE trinity_string SET `content_loc7`='El subnombre es demasiado largo, sobran %i caracteres.' WHERE entry=204;
UPDATE trinity_string SET `content_loc7`='Todavia no implementado.' WHERE entry=205;
UPDATE trinity_string SET `content_loc7`='Objeto \'%i\' \'%s\' añadido a la lista con maxcount \'%i\' y incrtime \'%i\' y extendedcost \'%i\'' WHERE entry=206;
UPDATE trinity_string SET `content_loc7`='Objeto \'%i\' no encontrado en la base de datos.' WHERE entry=207;
UPDATE trinity_string SET `content_loc7`='Objeto \'%i\' \'%s\' eliminado de la lista del vendedor.' WHERE entry=208;
UPDATE trinity_string SET `content_loc7`='Objeto \'%i\' no encontrado en lista del vendedor.' WHERE entry=209;
UPDATE trinity_string SET `content_loc7`='Objeto \'%u\' (con coste extendido %u) ya se encuentra en la lista del vendedor.' WHERE entry=210;
UPDATE trinity_string SET `content_loc7`='Hechizos de %s reiniciados.' WHERE entry=211;
UPDATE trinity_string SET `content_loc7`='Los hechizos de %s serán reinciados en el próximo inicio de sesión.' WHERE entry=212;
UPDATE trinity_string SET `content_loc7`='Talentos de %s reiniciados' WHERE entry=213;
UPDATE trinity_string SET `content_loc7`='Los talentos de %s serán reinciados en el próximo inicio de sesión.' WHERE entry=214;
UPDATE trinity_string SET `content_loc7`='Tus hechizos han sido reiniciados.' WHERE entry=215;
UPDATE trinity_string SET `content_loc7`='Tus talentos han sido reiniciados.' WHERE entry=216;
UPDATE trinity_string SET `content_loc7`='Opción desconocida \'%s\' para el comando .resetall. Introduce el nombre de la opción correctamente.' WHERE entry=217;
UPDATE trinity_string SET `content_loc7`='Los hechizos se reiniciarán para todos los jugadores al inicio de sesión. ¡Se recomienda estrictamente que reinicie la sesión!' WHERE entry=218;
UPDATE trinity_string SET `content_loc7`='Los talentos se reiniciarán para todos los jugadores al inicio de sesión. ¡Se recomienda estrictamente que reinicie la sesión!' WHERE entry=219;
UPDATE trinity_string SET `content_loc7`='Criatura (GUID: %u) Ningún waypoint encontrado.' WHERE entry=220;
UPDATE trinity_string SET `content_loc7`='Criatura (GUID: %u) Último waypoint no encontrado.' WHERE entry=221;
UPDATE trinity_string SET `content_loc7`='Criatura (GUID: %u) Ningún waypoint encontrado - usado \'wpguid\'. Intentando encontrarlo por su posición...' WHERE entry=222;
UPDATE trinity_string SET `content_loc7`='Criatura (GUID: %u) Ningún waypoints encontrados - Esto es un problema con la bd de MaNGOS (single float).' WHERE entry=223;
UPDATE trinity_string SET `content_loc7`='La criatura seleccionada es ignorada - se usa el GUID provisto' WHERE entry=224;
UPDATE trinity_string SET `content_loc7`='Criatura (GUID: %u) no encontrada' WHERE entry=225;
UPDATE trinity_string SET `content_loc7`='Debes seleccionar un waypoint visual.' WHERE entry=226;
UPDATE trinity_string SET `content_loc7`='No se han encontrado waypoints visuales' WHERE entry=227;
UPDATE trinity_string SET `content_loc7`='No se puede crear un waypoint visual con criaturaID: %d' WHERE entry=228;
UPDATE trinity_string SET `content_loc7`='Todos los waypoints visuales eliminados' WHERE entry=229;
UPDATE trinity_string SET `content_loc7`='No se puede crear un waypoint-criatura con ID: %d' WHERE entry=230;
UPDATE trinity_string SET `content_loc7`='No se ha definido GUID.' WHERE entry=231;
UPDATE trinity_string SET `content_loc7`='No se ha definido un número de waypoint.' WHERE entry=232;
UPDATE trinity_string SET `content_loc7`='Argumento requerido para \'%s\'.' WHERE entry=233;
UPDATE trinity_string SET `content_loc7`='Waypoint %i añadido al GUID: %d' WHERE entry=234;
UPDATE trinity_string SET `content_loc7`='Waypoint %d añadido.' WHERE entry=235;
UPDATE trinity_string SET `content_loc7`='Waypoint cambiado.' WHERE entry=236;
UPDATE trinity_string SET `content_loc7`='Waypoint %s modificado.' WHERE entry=237;
UPDATE trinity_string SET `content_loc7`='WP exportado correctamente.' WHERE entry=238;
UPDATE trinity_string SET `content_loc7`='No se han encontrado waypoints en la base de datos.' WHERE entry=239;
UPDATE trinity_string SET `content_loc7`='Archivo importado.' WHERE entry=240;
UPDATE trinity_string SET `content_loc7`='Waypoint eliminado.' WHERE entry=241;
UPDATE trinity_string SET `content_loc7`='Atención: No se puede eliminar el WP del mundo con el ID: %d' WHERE entry=242;
UPDATE trinity_string SET `content_loc7`='Esto ocurre si el waypoint está demasiado lejos de tu personaje.' WHERE entry=243;
UPDATE trinity_string SET `content_loc7`='El WP está eliminado de la base de datos, pero no del mundo aquí.' WHERE entry=244;
UPDATE trinity_string SET `content_loc7`='Desaparecerán despues de un reinicio del servidor.' WHERE entry=245;
UPDATE trinity_string SET `content_loc7`='Waypoint %d: Info de la criatura: %s, GUID: %d' WHERE entry=246;
UPDATE trinity_string SET `content_loc7`='Tiempo de Espera: %d' WHERE entry=247;
UPDATE trinity_string SET `content_loc7`='Modelo %d: %d' WHERE entry=248;
UPDATE trinity_string SET `content_loc7`='Gesto: %d' WHERE entry=249;
UPDATE trinity_string SET `content_loc7`='Hechizo: %d' WHERE entry=250;
UPDATE trinity_string SET `content_loc7`='Texto%d (ID: %i): %s' WHERE entry=251;
UPDATE trinity_string SET `content_loc7`='AIScript: %s' WHERE entry=252;
UPDATE trinity_string SET `content_loc7`='El renombrado del Jugador %s será solicitado en el próximo inicio de sesión.' WHERE entry=253;
UPDATE trinity_string SET `content_loc7`='El renombrado del Jugador %s (GUID #%u) será solicitado en el próximo inicio de sesión.' WHERE entry=254;
UPDATE trinity_string SET `content_loc7`='Waypoint-Criatura (GUID: %u) no encontrado' WHERE entry=255;
UPDATE trinity_string SET `content_loc7`='No se pudo encontrar el PNJ...' WHERE entry=256;
UPDATE trinity_string SET `content_loc7`='Tipo de movimiento de la criatura puesto a \'%s\', waypoints eliminados (si los hay).' WHERE entry=257;
UPDATE trinity_string SET `content_loc7`='Tipo de movimiento de la criatura puesto a \'%s\', waypoints no eliminados.' WHERE entry=258;
UPDATE trinity_string SET `content_loc7`='Valor incorrecto, Usa on (Activar) u off (Desactivar)' WHERE entry=259;
UPDATE trinity_string SET `content_loc7`='Valor guardado.' WHERE entry=260;
UPDATE trinity_string SET `content_loc7`='Valor guardado, puede que tengas que reingresar o limpiar la caché de tu cliente.' WHERE entry=261;
UPDATE trinity_string SET `content_loc7`='¡ID Areatrigger %u no encontrada!' WHERE entry=262;
UPDATE trinity_string SET `content_loc7`='Objetivo de mapa o coordenadas no válidos (X: %f Y: %f MapaId: %u)' WHERE entry=263;
UPDATE trinity_string SET `content_loc7`='Coordenadas de la zona no válidas (X: %f Y: %f AreaId: %u)' WHERE entry=264;
UPDATE trinity_string SET `content_loc7`='La zona %u (%s) es parte del mapa de la instancia %u (%s)' WHERE entry=265;
UPDATE trinity_string SET `content_loc7`='¡No se encontró nada!' WHERE entry=266;
UPDATE trinity_string SET `content_loc7`='¡No se encontró el Objeto!' WHERE entry=267;
UPDATE trinity_string SET `content_loc7`='¡No se encontró la Criatura!' WHERE entry=268;
UPDATE trinity_string SET `content_loc7`='Advertencia: Mob encontrado más de una vez - se te transportará al primero encontrado en la BD.' WHERE entry=269;
UPDATE trinity_string SET `content_loc7`='Criatura eliminada' WHERE entry=270;
UPDATE trinity_string SET `content_loc7`='Criatura movida' WHERE entry=271;
UPDATE trinity_string SET `content_loc7`='¡La criatura (GUID:%u) debe estar en el mismo mapa del jugador!' WHERE entry=272;
UPDATE trinity_string SET `content_loc7`='Objeto del Juego (GUID: %u) no encontrado' WHERE entry=273;
UPDATE trinity_string SET `content_loc7`='Objeto del Juego (GUID: %u) tiene referencias en la lista de objetos de la criatura no encontrada %u, no puede ser eliminado.' WHERE entry=274;
UPDATE trinity_string SET `content_loc7`='Objeto del Juego (GUID: %u) eliminado' WHERE entry=275;
UPDATE trinity_string SET `content_loc7`='Objeto del Juego |cffffffff|Hobjetojuego:%d|h[%s]|h|r (GUID: %u) girado' WHERE entry=276;
UPDATE trinity_string SET `content_loc7`='Objeto del Juego |cffffffff|Hobjetojuego:%d|h[%s]|h|r (GUID: %u) movido' WHERE entry=277;
UPDATE trinity_string SET `content_loc7`='Debes seleccionar un vendedor' WHERE entry=278;
UPDATE trinity_string SET `content_loc7`='Debe enviar el id para el objeto' WHERE entry=279;
UPDATE trinity_string SET `content_loc7`='El vendedor tiene demasiados objetos (máximo 128)' WHERE entry=280;
UPDATE trinity_string SET `content_loc7`='No puedes auto expulsarte, cierra la sesión.' WHERE entry=281;
UPDATE trinity_string SET `content_loc7`='Jugador %s expulsado.' WHERE entry=282;
UPDATE trinity_string SET `content_loc7`='Aceptar mensajes privados: %s' WHERE entry=284;
UPDATE trinity_string SET `content_loc7`='Aceptar mensajes privados: Activado' WHERE entry=285;
UPDATE trinity_string SET `content_loc7`='Aceptar Mensajes privados: Desactivado' WHERE entry=286;
UPDATE trinity_string SET `content_loc7`='Criatura (GUID: %u) no encontrada' WHERE entry=287;
UPDATE trinity_string SET `content_loc7`='Tickets: %i - mostrar nuevos tickets: %s\n' WHERE entry=288;
UPDATE trinity_string SET `content_loc7`='Nuevo ticket de %s' WHERE entry=289;
UPDATE trinity_string SET `content_loc7`='Ticket de %s (Actualizado: %s):\n%s' WHERE entry=290;
UPDATE trinity_string SET `content_loc7`='Mostrar nuevo ticket: ACTIVADO' WHERE entry=291;
UPDATE trinity_string SET `content_loc7`='Mostrar nuevo ticket: DESACTIVADO' WHERE entry=292;
UPDATE trinity_string SET `content_loc7`='El ticket %i no existe.' WHERE entry=293;
UPDATE trinity_string SET `content_loc7`='Todos los tickets eliminados.' WHERE entry=294;
UPDATE trinity_string SET `content_loc7`='Personaje %s Ticket eliminado.' WHERE entry=295;
UPDATE trinity_string SET `content_loc7`='Ticket borrado.' WHERE entry=296;
UPDATE trinity_string SET `content_loc7`='Distancia de Reaparición cambiada a: %f' WHERE entry=297;
UPDATE trinity_string SET `content_loc7`='Tiempo de Reaparición cambiado a: %i' WHERE entry=298;
UPDATE trinity_string SET `content_loc7`='¡El honor de %s se ha establecido en %u!' WHERE entry=299;
UPDATE trinity_string SET `content_loc7`='Tu chat ha sido desactivado durante %u minutos. Motivo: %s.' WHERE entry=300;
UPDATE trinity_string SET `content_loc7`='Has desactivado el chat de %s durante %u minutos. Motivo: %s.' WHERE entry=301;
UPDATE trinity_string SET `content_loc7`='El chat del jugador ya está activado.' WHERE entry=302;
UPDATE trinity_string SET `content_loc7`='Tu chat ha sido activado.' WHERE entry=303;
UPDATE trinity_string SET `content_loc7`='Has activado el chat de %s.' WHERE entry=304;
UPDATE trinity_string SET `content_loc7`='¡Facción %s (%u) la reputación de %s se estableció en %5d!' WHERE entry=305;
UPDATE trinity_string SET `content_loc7`='¡Los puntos de arena de %s se establecieron en %u!' WHERE entry=306;
UPDATE trinity_string SET `content_loc7`='¡Facción no encontrada!' WHERE entry=307;
UPDATE trinity_string SET `content_loc7`='¡Facción %i desconocida!' WHERE entry=308;
UPDATE trinity_string SET `content_loc7`='Parámetro %s inválido' WHERE entry=309;
UPDATE trinity_string SET `content_loc7`='delta debe estar entre 0 y %d (inclusivo)' WHERE entry=310;
UPDATE trinity_string SET `content_loc7`='%d - |cffffffff|Hfacción:%d|h[%s]|h|r' WHERE entry=311;
UPDATE trinity_string SET `content_loc7`=' [visible]' WHERE entry=312;
UPDATE trinity_string SET `content_loc7`=' [en guerra]' WHERE entry=313;
UPDATE trinity_string SET `content_loc7`=' [paz forzada]' WHERE entry=314;
UPDATE trinity_string SET `content_loc7`=' [oculta]' WHERE entry=315;
UPDATE trinity_string SET `content_loc7`=' [invisibilidad forzada]' WHERE entry=316;
UPDATE trinity_string SET `content_loc7`=' [inactiva]' WHERE entry=317;
UPDATE trinity_string SET `content_loc7`='Odiado' WHERE entry=318;
UPDATE trinity_string SET `content_loc7`='Hostil' WHERE entry=319;
UPDATE trinity_string SET `content_loc7`='Enemigo' WHERE entry=320;
UPDATE trinity_string SET `content_loc7`='Neutral' WHERE entry=321;
UPDATE trinity_string SET `content_loc7`='Amistoso' WHERE entry=322;
UPDATE trinity_string SET `content_loc7`='Honrado' WHERE entry=323;
UPDATE trinity_string SET `content_loc7`='Reverenciado' WHERE entry=324;
UPDATE trinity_string SET `content_loc7`='Exaltado' WHERE entry=325;
UPDATE trinity_string SET `content_loc7`='Facción %s (%u) no puede tener reputación.' WHERE entry=326;
UPDATE trinity_string SET `content_loc7`=' [sin reputación]' WHERE entry=327;
UPDATE trinity_string SET `content_loc7`='Personajes en la cuenta %s (Id: %u)' WHERE entry=328;
UPDATE trinity_string SET `content_loc7`='  %s (GUID %u)' WHERE entry=329;
UPDATE trinity_string SET `content_loc7`='¡Ningún jugador encontrado!' WHERE entry=330;
UPDATE trinity_string SET `content_loc7`='Coste extendido del objeto %u inexistente' WHERE entry=331;
UPDATE trinity_string SET `content_loc7`='Modo MJ está ACTIVADO' WHERE entry=332;
UPDATE trinity_string SET `content_loc7`='Modo MJ está DESACTIVADO' WHERE entry=333;
UPDATE trinity_string SET `content_loc7`='Marca de MJ en el chat está ACTIVADA' WHERE entry=334;
UPDATE trinity_string SET `content_loc7`='Marca de MJ en el chat está DESACTIVADA' WHERE entry=335;
UPDATE trinity_string SET `content_loc7`='Has reparado todos los objetos de %s.' WHERE entry=336;
UPDATE trinity_string SET `content_loc7`='Todos tus objetos reparados por %s.' WHERE entry=337;
UPDATE trinity_string SET `content_loc7`='Activas el modo caminar sobre agua %s para %s.' WHERE entry=338;
UPDATE trinity_string SET `content_loc7`='Tienes el modo caminar sobre agua %s por %s.' WHERE entry=339;
UPDATE trinity_string SET `content_loc7`='%s esta siguiéndote ahora.' WHERE entry=340;
UPDATE trinity_string SET `content_loc7`='%s no te está siguiendo.' WHERE entry=341;
UPDATE trinity_string SET `content_loc7`='%s dejó de seguirte.' WHERE entry=342;
UPDATE trinity_string SET `content_loc7`='Criatura (Entry: %u) no puede ser domesticada.' WHERE entry=343;
UPDATE trinity_string SET `content_loc7`='Ya tienes una mascota.' WHERE entry=344;
UPDATE trinity_string SET `content_loc7`='La personalización forzada para el jugador %s será requerida al siguiente inicio de sesión.' WHERE entry=345;
UPDATE trinity_string SET `content_loc7`='La personalización forzada para el jugador %s (GUID #%u) será requerida al siguiente inicio de sesión.' WHERE entry=346;
UPDATE trinity_string SET `content_loc7`='¡Ruta de vuelo con ID %u no encontrada!' WHERE entry=347;
UPDATE trinity_string SET `content_loc7`='Objeto de Juego (Entrada: %u) tiene datos no válidos y no puede aparecer' WHERE entry=348;
UPDATE trinity_string SET `content_loc7`='%d (idx:%d) - |cffffffff|Htítulo:%d|h[%s %s]|h|r %s %s ' WHERE entry=349;
UPDATE trinity_string SET `content_loc7`='%d (idx:%d) - [%s %s] %s %s ' WHERE entry=350;
UPDATE trinity_string SET `content_loc7`='¡No se encontraron títulos!' WHERE entry=351;
UPDATE trinity_string SET `content_loc7`='ID de título inválido: %u' WHERE entry=352;
UPDATE trinity_string SET `content_loc7`='Título %u (%s) añadido a lista de títulos conocidos para el jugador %s.' WHERE entry=353;
UPDATE trinity_string SET `content_loc7`='Título %u (%s) eliminado de lista de títulos conocidos para el jugador %s.' WHERE entry=354;
UPDATE trinity_string SET `content_loc7`='Título %u (%s) establecido como título seleccionado para el jugador %s.' WHERE entry=355;
UPDATE trinity_string SET `content_loc7`='Título seleccionado para el jugador %s se ha reiniciado como no conocido.' WHERE entry=356;
UPDATE trinity_string SET `content_loc7`='|cffff0000[Mensaje del Sistema]:|rScripts recargados' WHERE entry=400;
UPDATE trinity_string SET `content_loc7`='Cambiaste el nivel de seguridad de la cuenta %s a %i.' WHERE entry=401;
UPDATE trinity_string SET `content_loc7`='%s cambió tu nivel de seguridad a %i.' WHERE entry=402;
UPDATE trinity_string SET `content_loc7`='No tienes suficiente nivel de seguridad para eso.' WHERE entry=403;
UPDATE trinity_string SET `content_loc7`='Movimiento de la criatura desactivado.' WHERE entry=404;
UPDATE trinity_string SET `content_loc7`='Movimiento de la criatura activado.' WHERE entry=405;
UPDATE trinity_string SET `content_loc7`='El clima no puede cambiarse para esta zona.' WHERE entry=406;
UPDATE trinity_string SET `content_loc7`='El sistema de clima está desactivado en este servidor.' WHERE entry=407;
UPDATE trinity_string SET `content_loc7`='%s ha sido baneado por %s. Motivo: %s.' WHERE entry=408;
UPDATE trinity_string SET `content_loc7`='%s fué baneado permanentemente por %s.' WHERE entry=409;
UPDATE trinity_string SET `content_loc7`='%s %s no encontrado' WHERE entry=410;
UPDATE trinity_string SET `content_loc7`='%s desbaneado.' WHERE entry=411;
UPDATE trinity_string SET `content_loc7`='Hubo un error al eliminar el baneo a %s.' WHERE entry=412;
UPDATE trinity_string SET `content_loc7`='Cuenta inexistente: %s' WHERE entry=413;
UPDATE trinity_string SET `content_loc7`='No se encontró el personaje.' WHERE entry=414;
UPDATE trinity_string SET `content_loc7`='No hay ninguna IP en la lista de baneo.' WHERE entry=415;
UPDATE trinity_string SET `content_loc7`='La cuenta %s nunca ha sido baneada' WHERE entry=416;
UPDATE trinity_string SET `content_loc7`='Historial de baneo para la cuenta %s:' WHERE entry=417;
UPDATE trinity_string SET `content_loc7`='Fecha del baneo: %s Hora: %s Aún Activo: %s Motivo: %s Puesto por: %s' WHERE entry=418;
UPDATE trinity_string SET `content_loc7`='Info.' WHERE entry=419;
UPDATE trinity_string SET `content_loc7`='Nunca' WHERE entry=420;
UPDATE trinity_string SET `content_loc7`='Si' WHERE entry=421;
UPDATE trinity_string SET `content_loc7`='No' WHERE entry=422;
UPDATE trinity_string SET `content_loc7`='IP: %s\nFecha Baneo: %s\nFecha Desbaneo: %s\nTiempo restante: %s\nMotivo: %s\nPuesto por: %s' WHERE entry=423;
UPDATE trinity_string SET `content_loc7`='No hay baneos de IP concidentes.' WHERE entry=424;
UPDATE trinity_string SET `content_loc7`='No hay cuenta coincidente.' WHERE entry=425;
UPDATE trinity_string SET `content_loc7`='No hay una cuenta baneada al que pertenezca un personaje coincidente.' WHERE entry=426;
UPDATE trinity_string SET `content_loc7`='Las siguientes IPs coinciden con la consulta:' WHERE entry=427;
UPDATE trinity_string SET `content_loc7`='Las siguientes cuentas coinciden con la consulta:' WHERE entry=428;
UPDATE trinity_string SET `content_loc7`='Has aprendido demasiados Hechizos/Habilidades.' WHERE entry=429;
UPDATE trinity_string SET `content_loc7`='Has aprendido todos los hechizos de tu clase.' WHERE entry=430;
UPDATE trinity_string SET `content_loc7`='Has aprendido todos los talentos de tu clase.' WHERE entry=431;
UPDATE trinity_string SET `content_loc7`='Has aprendido todos los idiomas.' WHERE entry=432;
UPDATE trinity_string SET `content_loc7`='Has aprendido todas las habilidades y recetas.' WHERE entry=433;
UPDATE trinity_string SET `content_loc7`='No se pudo encontrar \'%s\'' WHERE entry=434;
UPDATE trinity_string SET `content_loc7`='Id de objeto no válido: %u' WHERE entry=435;
UPDATE trinity_string SET `content_loc7`='¡Objetos no encontrados!' WHERE entry=436;
UPDATE trinity_string SET `content_loc7`='Id no válido del objeto de juego: %u' WHERE entry=437;
UPDATE trinity_string SET `content_loc7`='Objetos encontrados %u: %u ( inventario %u correo %u subasta %u hermandad %u)' WHERE entry=438;
UPDATE trinity_string SET `content_loc7`='Objetos de Juego encontrados %u: %u ' WHERE entry=439;
UPDATE trinity_string SET `content_loc7`='Id no válida de la criatura: %u' WHERE entry=440;
UPDATE trinity_string SET `content_loc7`='Criaturas encontradas %u: %u ' WHERE entry=441;
UPDATE trinity_string SET `content_loc7`='¡No se encontró el área!' WHERE entry=442;
UPDATE trinity_string SET `content_loc7`='¡No se encontraron conjuntos de objetos!' WHERE entry=443;
UPDATE trinity_string SET `content_loc7`='¡No se encontraron habilidades!' WHERE entry=444;
UPDATE trinity_string SET `content_loc7`='¡No se encontraron hechizos!' WHERE entry=445;
UPDATE trinity_string SET `content_loc7`='¡No se encontraron misiones!' WHERE entry=446;
UPDATE trinity_string SET `content_loc7`='¡No se encontraron criaturas!' WHERE entry=447;
UPDATE trinity_string SET `content_loc7`='¡No se encontraron objetos de juego!' WHERE entry=448;
UPDATE trinity_string SET `content_loc7`='Cementerio #%u no existe.' WHERE entry=449;
UPDATE trinity_string SET `content_loc7`='Cementerio #%u ya enlazado a la zona #%u (actual).' WHERE entry=450;
UPDATE trinity_string SET `content_loc7`='Cementerio #%u enlazado a la zona #%u (actual).' WHERE entry=451;
UPDATE trinity_string SET `content_loc7`='Cementerio #%u no puede ser enlazado a la subzona o zona inexistente #%u (error interno).' WHERE entry=452;
UPDATE trinity_string SET `content_loc7`='Ninguna facción en el Cementerio con id= #%u , repara la BD.' WHERE entry=454;
UPDATE trinity_string SET `content_loc7`='El equipo no es válido, por favor repare la base de datos.' WHERE entry=455;
UPDATE trinity_string SET `content_loc7`='cualquiera' WHERE entry=456;
UPDATE trinity_string SET `content_loc7`='alianza' WHERE entry=457;
UPDATE trinity_string SET `content_loc7`='horda' WHERE entry=458;
UPDATE trinity_string SET `content_loc7`='Cementerio #%u (facción: %s) está más cerca de la zona enlazada #%u.' WHERE entry=459;
UPDATE trinity_string SET `content_loc7`='Zona #%u no tiene cementerios enlazados.' WHERE entry=460;
UPDATE trinity_string SET `content_loc7`='Zona #%u no tiene cementerios enlazados para la facción: %s.' WHERE entry=461;
UPDATE trinity_string SET `content_loc7`='¡Localización de teletransporte ya existe!' WHERE entry=462;
UPDATE trinity_string SET `content_loc7`='Localización de teletransporte añadida.' WHERE entry=463;
UPDATE trinity_string SET `content_loc7`='Localización de teletransporte NO añadida: error de base de datos.' WHERE entry=464;
UPDATE trinity_string SET `content_loc7`='Localización de teletransporte eliminada.' WHERE entry=465;
UPDATE trinity_string SET `content_loc7`='¡Rutas de vuelo no encontradas!' WHERE entry=466;
UPDATE trinity_string SET `content_loc7`='Unidad objetivo tiene %d auras:' WHERE entry=467;
UPDATE trinity_string SET `content_loc7`='id: %d efMasc: %d cargas: %d pila: %d slot %d duración: %d duraciónmáx: %d' WHERE entry=468;
UPDATE trinity_string SET `content_loc7`='Unidad objetivo tiene %d auras del tipo %d:' WHERE entry=469;
UPDATE trinity_string SET `content_loc7`='id: %d ef: %d cantidad: %d' WHERE entry=470;
UPDATE trinity_string SET `content_loc7`='Misión %u no encontrada.' WHERE entry=471;
UPDATE trinity_string SET `content_loc7`='Misión %u se inicia con objeto. Para que funcione correctamente, por favor, añada el objeto al inventario e inicie la misión en modo normal: .additem %u' WHERE entry=472;
UPDATE trinity_string SET `content_loc7`='Mision eliminada.' WHERE entry=473;
UPDATE trinity_string SET `content_loc7`=' [recompensada]' WHERE entry=474;
UPDATE trinity_string SET `content_loc7`=' [completa]' WHERE entry=475;
UPDATE trinity_string SET `content_loc7`=' [activa]' WHERE entry=476;
UPDATE trinity_string SET `content_loc7`='Modo Vuelo de %s %s' WHERE entry=477;
UPDATE trinity_string SET `content_loc7`='Opcode %u enviado a %s' WHERE entry=478;
UPDATE trinity_string SET `content_loc7`='¡Personaje cargado correctamente!' WHERE entry=479;
UPDATE trinity_string SET `content_loc7`='¡Fallo al cargar el personaje!' WHERE entry=480;
UPDATE trinity_string SET `content_loc7`='¡Personaje volcado correctamente!' WHERE entry=481;
UPDATE trinity_string SET `content_loc7`='¡Fallo al volcar el personaje!' WHERE entry=482;
UPDATE trinity_string SET `content_loc7`='¡Hechizo %u roto y no se permite lanzar o aprender!' WHERE entry=483;
UPDATE trinity_string SET `content_loc7`='Habilidad %u (%s) para el jugador %s puesta a %u y el máximo puesto en %u (sin bonus (talentos) permanentes).' WHERE entry=484;
UPDATE trinity_string SET `content_loc7`='El jugador %s debe tener la habilidad %u (%s) antes de usar este comando.' WHERE entry=485;
UPDATE trinity_string SET `content_loc7`='Id de habilidad no válida (%u)' WHERE entry=486;
UPDATE trinity_string SET `content_loc7`='Aprendiste los hechizos/habilidades de MJ predeterminados' WHERE entry=487;
UPDATE trinity_string SET `content_loc7`='Ya conoces ese hechizo.' WHERE entry=488;
UPDATE trinity_string SET `content_loc7`='El objetivo(%s) ya conoce ese hechizo.' WHERE entry=489;
UPDATE trinity_string SET `content_loc7`='%s no conoce ese hechizo.' WHERE entry=490;
UPDATE trinity_string SET `content_loc7`='Ya olvidaste ese hechizo.' WHERE entry=491;
UPDATE trinity_string SET `content_loc7`='La reutilización para todos los hechizos fué eliminada para %s.' WHERE entry=492;
UPDATE trinity_string SET `content_loc7`='Reutilización del hechizo %u eliminada para %s.' WHERE entry=493;
UPDATE trinity_string SET `content_loc7`='Comando : Additem, itemId = %i, cantidad = %i' WHERE entry=494;
UPDATE trinity_string SET `content_loc7`='Comando : Additemset, itemsetId = %i' WHERE entry=495;
UPDATE trinity_string SET `content_loc7`='Eliminado IDobjeto = %i, cantidad = %i de %s' WHERE entry=496;
UPDATE trinity_string SET `content_loc7`='No se puede crear objeto \'%i\' (cantidad: %i)' WHERE entry=497;
UPDATE trinity_string SET `content_loc7`='¡Necesitas proporcionar un nombre de Hermandad!' WHERE entry=498;
UPDATE trinity_string SET `content_loc7`='¡Jugador no encontrado!' WHERE entry=499;
UPDATE trinity_string SET `content_loc7`='¡El jugador ya esta en una hermandad!' WHERE entry=500;
UPDATE trinity_string SET `content_loc7`='¡No se creo la hermandad! (¿ya existe?)' WHERE entry=501;
UPDATE trinity_string SET `content_loc7`='Ningún objeto del conjunto \'%u\' encontrado.' WHERE entry=502;
UPDATE trinity_string SET `content_loc7`='La distancia es: (3D) %f (2D) %f (3D Exacto) %f (2D Exacto) %f yardas.' WHERE entry=503;
UPDATE trinity_string SET `content_loc7`='Objeto \'%i\' \'%s\' Casilla Objeto %i' WHERE entry=504;
UPDATE trinity_string SET `content_loc7`='Objeto \'%i\' no existe.' WHERE entry=505;
UPDATE trinity_string SET `content_loc7`='Objeto \'%i\' \'%s\' añadido a ranura %i' WHERE entry=506;
UPDATE trinity_string SET `content_loc7`='¡Fallo de guardado del objeto!' WHERE entry=507;
UPDATE trinity_string SET `content_loc7`='%d - propietario: %s (guid: %u cuenta: %u ) %s' WHERE entry=508;
UPDATE trinity_string SET `content_loc7`='%d - remitente: %s (guid: %u cuenta: %u) receptor: %s (guid: %u cuenta: %u) %s' WHERE entry=509;
UPDATE trinity_string SET `content_loc7`='%d - propietario: %s (guid: %u cuenta: %u) %s' WHERE entry=510;
UPDATE trinity_string SET `content_loc7`='¡Tipo de enlace incorrecto!' WHERE entry=511;
UPDATE trinity_string SET `content_loc7`='%d - |cffffffff|Hobjeto:%d:0:0:0:0:0:0:0:0|h[%s]|h|r ' WHERE entry=512;
UPDATE trinity_string SET `content_loc7`='%d - |cffffffff|Hmisión:%d:%d|h[%s]|h|r %s' WHERE entry=513;
UPDATE trinity_string SET `content_loc7`='%d - |cffffffff|Hentrada criatura:%d|h[%s]|h|r ' WHERE entry=514;
UPDATE trinity_string SET `content_loc7`='%d - |cffffffff|Hcriatura:%d|h[%s X:%f Y:%f Z:%f IdMapa:%d]|h|r ' WHERE entry=515;
UPDATE trinity_string SET `content_loc7`='%d - |cffffffff|Hentrada objeto de juego:%d|h[%s]|h|r ' WHERE entry=516;
UPDATE trinity_string SET `content_loc7`='%d (Entrada: %d) - |cffffffff|Hobjeto de juego:%d|h[%s X:%f Y:%f Z:%f IdMapa:%d]|h|r ' WHERE entry=517;
UPDATE trinity_string SET `content_loc7`='%d - |cffffffff|Hconj. objetos:%d|h[%s %s]|h|r ' WHERE entry=518;
UPDATE trinity_string SET `content_loc7`='|cffffffff|Htele:%s|h[%s]|h|r ' WHERE entry=519;
UPDATE trinity_string SET `content_loc7`='%d - |cffffffff|Hhechizo:%d|h[%s]|h|r ' WHERE entry=520;
UPDATE trinity_string SET `content_loc7`='%d - |cffffffff|Hhabilidad:%d|h[%s %s]|h|r %s %s' WHERE entry=521;
UPDATE trinity_string SET `content_loc7`='Objeto de Juego (Entrada: %u) no encontrado' WHERE entry=522;
UPDATE trinity_string SET `content_loc7`='>> Objeto de Juego %s (GUID: %u) en %f %f %f. Orientación %f.' WHERE entry=523;
UPDATE trinity_string SET `content_loc7`='Objeto seleccionado:\n|cffffffff|Hobjeto de juego:%d|h[%s]|h|r GUID: %u ID: %u\nX: %f Y: %f Z: %f Id Mapa: %u\nOrientación: %f\nMáscara de fase %u' WHERE entry=524;
UPDATE trinity_string SET `content_loc7`='>> Añadir Objeto de Juego \'%i\' (%s) (GUID: %i) añadido en \'%f %f %f\'.' WHERE entry=525;
UPDATE trinity_string SET `content_loc7`='%s (guidbajo: %u) pila de generadores de movimiento:' WHERE entry=526;
UPDATE trinity_string SET `content_loc7`='   Reposo' WHERE entry=527;
UPDATE trinity_string SET `content_loc7`='   Aleatorio' WHERE entry=528;
UPDATE trinity_string SET `content_loc7`='   Waypoint' WHERE entry=529;
UPDATE trinity_string SET `content_loc7`='   Aleatorio animal' WHERE entry=530;
UPDATE trinity_string SET `content_loc7`='   Confundido' WHERE entry=531;
UPDATE trinity_string SET `content_loc7`='   Apuntado al jugador %s (guidbajo %u)' WHERE entry=532;
UPDATE trinity_string SET `content_loc7`='   Apuntado a la criatura %s (guidbajo %u)' WHERE entry=533;
UPDATE trinity_string SET `content_loc7`='   Apuntado a <NULL>' WHERE entry=534;
UPDATE trinity_string SET `content_loc7`='   Movimiento origen a (X:%f Y:%f Z:%f)' WHERE entry=535;
UPDATE trinity_string SET `content_loc7`='   Movimiento origen usado para jugador?!?' WHERE entry=536;
UPDATE trinity_string SET `content_loc7`='   Ruta de vuelo' WHERE entry=537;
UPDATE trinity_string SET `content_loc7`='   Generador de movimiento desconocido (%u)' WHERE entry=538;
UPDATE trinity_string SET `content_loc7`='Jugador Seleccionado PNJ\r\nGUID de BD: %u, GUID actual: %u.\r\nFacción: %u.\r\nnpcFlags: %u.\r\nEntrada: %u.\r\nDisplayID: %u (Nativo: %u).' WHERE entry=539;
UPDATE trinity_string SET `content_loc7`='Nivel: %u.' WHERE entry=540;
UPDATE trinity_string SET `content_loc7`='Vida (base): %u. (max): %u. (Actual): %u.' WHERE entry=541;
UPDATE trinity_string SET `content_loc7`='Flags de unidad: %u.\nFlags dinámicos: %u.\nPlantilla facción: %u.' WHERE entry=542;
UPDATE trinity_string SET `content_loc7`='Botín: %u Robar: %u Desollar: %u' WHERE entry=543;
UPDATE trinity_string SET `content_loc7`='Posición: %f %f %f.' WHERE entry=544;
UPDATE trinity_string SET `content_loc7`='¡*** Es un vendedor!' WHERE entry=545;
UPDATE trinity_string SET `content_loc7`='¡*** Es un entrenador!' WHERE entry=546;
UPDATE trinity_string SET `content_loc7`='ID Mazmorra: %u' WHERE entry=547;
UPDATE trinity_string SET `content_loc7`='Jugador%s %s (guid: %u) Cuenta: %s (id: %u) Email: %s NivelMJ: %u Última IP: %s Último acceso: %s Latencia: %ums' WHERE entry=548;
UPDATE trinity_string SET `content_loc7`='Raza: %s Clase: %s Tiempo Jugado: %s Nivel: %u Dinero: %ug%us%uc' WHERE entry=549;
UPDATE trinity_string SET `content_loc7`='Tiempo de silencio restante: %s, Tiempo de baneo restante: %s' WHERE entry=550;
UPDATE trinity_string SET `content_loc7`='%s ha explorado ahora todas las zonas.' WHERE entry=551;
UPDATE trinity_string SET `content_loc7`='%s no tiene más zonas exploradas.' WHERE entry=552;
UPDATE trinity_string SET `content_loc7`='%s ha explorado todas las zonas para ti.' WHERE entry=553;
UPDATE trinity_string SET `content_loc7`='% ha ocultado todas las zonas para ti.' WHERE entry=554;
UPDATE trinity_string SET `content_loc7`='Planeo habilitado' WHERE entry=555;
UPDATE trinity_string SET `content_loc7`='Planeo deshabilitado' WHERE entry=556;
UPDATE trinity_string SET `content_loc7`='%s te ha subido de nivel al (%i)' WHERE entry=557;
UPDATE trinity_string SET `content_loc7`='%s te ha bajado de nivel al (%i)' WHERE entry=558;
UPDATE trinity_string SET `content_loc7`='%s te ha reiniciado tu progreso del nivel.' WHERE entry=559;
UPDATE trinity_string SET `content_loc7`='Se ha establecido el area como explorada.' WHERE entry=560;
UPDATE trinity_string SET `content_loc7`='Se ha establecido el area como no explorada.' WHERE entry=561;
UPDATE trinity_string SET `content_loc7`='GUID=%i Act. de Indice: %i, valor:  %i.' WHERE entry=562;
UPDATE trinity_string SET `content_loc7`='Cambias GUID=%i Act. de Indice: %i valor a %i.' WHERE entry=563;
UPDATE trinity_string SET `content_loc7`='El índice del valor %u es demasiado grande para %u(cuenta: %u).' WHERE entry=564;
UPDATE trinity_string SET `content_loc7`='Puesto %u uint32 Valor:[OPCODE]:%u [VALOR]:%u' WHERE entry=565;
UPDATE trinity_string SET `content_loc7`='Pones %u Campo:%u a uint32 Valor: %u' WHERE entry=566;
UPDATE trinity_string SET `content_loc7`='Puesto %u float Valor:[OPCODE]:%u [VALOR]:%f' WHERE entry=567;
UPDATE trinity_string SET `content_loc7`='Pones %u Campo:%i a float Valor: %f' WHERE entry=568;
UPDATE trinity_string SET `content_loc7`='Obtienes %u uint32 Valor:[OPCODE]:%u [VALOR]:%u' WHERE entry=569;
UPDATE trinity_string SET `content_loc7`='El valor uint32 de %u en %u es: %u' WHERE entry=570;
UPDATE trinity_string SET `content_loc7`='Obtienes %u float Valor:[OPCODE]:%u [VALOR]:%f' WHERE entry=571;
UPDATE trinity_string SET `content_loc7`='El float de %u valor en %u es: %f' WHERE entry=572;
UPDATE trinity_string SET `content_loc7`='.Set32Bit:[OPCODE]:%u [VALOR]:%u' WHERE entry=573;
UPDATE trinity_string SET `content_loc7`='Pones Bit de Campo:%u a Valor: %u' WHERE entry=574;
UPDATE trinity_string SET `content_loc7`='.Mod32Value:[OPCODE]:%u [VALOR]:%i' WHERE entry=575;
UPDATE trinity_string SET `content_loc7`='Modificaste el valor del campo:%u a Valor: %u' WHERE entry=576;
UPDATE trinity_string SET `content_loc7`='Ahora eres invisible.' WHERE entry=577;
UPDATE trinity_string SET `content_loc7`='Ahora eres visible.' WHERE entry=578;
UPDATE trinity_string SET `content_loc7`='El jugador o criatura seleccionados no tienen víctima.' WHERE entry=579;
UPDATE trinity_string SET `content_loc7`='Jugador %s aprendió todos los hechizos por defecto de su raza/clase y los hechizos de recompensa al completar misiones.' WHERE entry=580;
UPDATE trinity_string SET `content_loc7`='Encontrados objetos del juego cercanos (a distancia %f): %u' WHERE entry=581;
UPDATE trinity_string SET `content_loc7`='Tiempo de reaparición: Total:%s Restante:%s' WHERE entry=582;
UPDATE trinity_string SET `content_loc7`='%d - |cffffffff|Hevento juego:%d|h[%s]|h|r%s' WHERE entry=583;
UPDATE trinity_string SET `content_loc7`='¡Evento no encontrado!' WHERE entry=584;
UPDATE trinity_string SET `content_loc7`='¡El evento no existe!' WHERE entry=585;
UPDATE trinity_string SET `content_loc7`='Evento %u: %s%s\nInicio: %s Fin: %s Ocurrencia: %s Longitud: %s\nSiguiente cambio de estado: %s' WHERE entry=586;
UPDATE trinity_string SET `content_loc7`='¡Evento %u ya activo!' WHERE entry=587;
UPDATE trinity_string SET `content_loc7`='¡Evento %u no está activo!' WHERE entry=588;
UPDATE trinity_string SET `content_loc7`='   Punto de movimiento a (X:%f Y:%f Z:%f)' WHERE entry=589;
UPDATE trinity_string SET `content_loc7`='   Movimiento de miedo' WHERE entry=590;
UPDATE trinity_string SET `content_loc7`='   Movimiento de distracción' WHERE entry=591;
UPDATE trinity_string SET `content_loc7`='Has aprendido todos los hechizos en la profesión: %s' WHERE entry=592;
UPDATE trinity_string SET `content_loc7`='Cuentas baneadas actualmente:' WHERE entry=593;
UPDATE trinity_string SET `content_loc7`='|    Cuenta     | Fecha Baneo  |Fecha Desbaneo|  Baneado Por  | Motivo Baneo  |' WHERE entry=594;
UPDATE trinity_string SET `content_loc7`='IPs baneadas actualmente:' WHERE entry=595;
UPDATE trinity_string SET `content_loc7`='|      IP       | Fecha Baneo  |Fecha Desbaneo|  Baneado Por  | Motivo Baneo  |' WHERE entry=596;
UPDATE trinity_string SET `content_loc7`='Maestros de Juego actualmente:' WHERE entry=597;
UPDATE trinity_string SET `content_loc7`='|    Cuenta     |  MJ  |' WHERE entry=598;
UPDATE trinity_string SET `content_loc7`='No hay maestros de juego.' WHERE entry=599;
UPDATE trinity_string SET `content_loc7`='¡La Alianza gana!' WHERE entry=600;
UPDATE trinity_string SET `content_loc7`='¡La Horda gana!' WHERE entry=601;
UPDATE trinity_string SET `content_loc7`='La batalla por la Garganta Grito de Guerra comenzará en 1 minuto.' WHERE entry=602;
UPDATE trinity_string SET `content_loc7`='La batalla por la Garganta Grito de Guerra comenzará en 30 segundos. ¡Preparaos!' WHERE entry=603;
UPDATE trinity_string SET `content_loc7`='¡La batalla por la Garganta Grito de Guerra ha comenzado!' WHERE entry=604;
UPDATE trinity_string SET `content_loc7`='¡$n capturó la bandera de la Horda!' WHERE entry=605;
UPDATE trinity_string SET `content_loc7`='¡$n capturó la bandera de la Alianza!' WHERE entry=606;
UPDATE trinity_string SET `content_loc7`='¡$n perdió la bandera de la Horda!' WHERE entry=607;
UPDATE trinity_string SET `content_loc7`='¡$n perdió la bandera de la Alianza!' WHERE entry=608;
UPDATE trinity_string SET `content_loc7`='¡$n devolvió la bandera de la Alianza a su base!' WHERE entry=609;
UPDATE trinity_string SET `content_loc7`='¡$n devolvió la bandera de la Horda a su base!' WHERE entry=610;
UPDATE trinity_string SET `content_loc7`='¡La bandera de la Horda ha sido capturada por $n!' WHERE entry=611;
UPDATE trinity_string SET `content_loc7`='¡La bandera de la Alianza ha sido capturada por $n!' WHERE entry=612;
UPDATE trinity_string SET `content_loc7`='Las banderas ahora están en sus bases.' WHERE entry=613;
UPDATE trinity_string SET `content_loc7`='¡La bandera de la Alianza está ahora en su base!' WHERE entry=614;
UPDATE trinity_string SET `content_loc7`='¡La bandera de la Horda está ahora en su base!' WHERE entry=615;
UPDATE trinity_string SET `content_loc7`='La batalla por el Ojo de la Tormenta comenzará en 1 minuto.' WHERE entry=636;
UPDATE trinity_string SET `content_loc7`='La batalla por el Ojo de la Tormenta comenzará en 30 segundos.' WHERE entry=637;
UPDATE trinity_string SET `content_loc7`='¡La batalla por el Ojo de la Tormenta ha comenzado!' WHERE entry=638;
UPDATE trinity_string SET `content_loc7`='La Alianza' WHERE entry=650;
UPDATE trinity_string SET `content_loc7`='La Horda' WHERE entry=651;
UPDATE trinity_string SET `content_loc7`='los establos' WHERE entry=652;
UPDATE trinity_string SET `content_loc7`='la herrería' WHERE entry=653;
UPDATE trinity_string SET `content_loc7`='la granja' WHERE entry=654;
UPDATE trinity_string SET `content_loc7`='el aserradero' WHERE entry=655;
UPDATE trinity_string SET `content_loc7`='la mina' WHERE entry=656;
UPDATE trinity_string SET `content_loc7`='%s ha capturado %s' WHERE entry=657;
UPDATE trinity_string SET `content_loc7`='$n ha defendido %s' WHERE entry=658;
UPDATE trinity_string SET `content_loc7`='$n ha asaltado %s' WHERE entry=659;
UPDATE trinity_string SET `content_loc7`='¡$n reclama %s! Si nadie lo impide, ¡%s lo controlará en 1 minuto!' WHERE entry=660;
UPDATE trinity_string SET `content_loc7`='La batalla por la Cuenca de Arathi comenzará en 1 minuto.' WHERE entry=661;
UPDATE trinity_string SET `content_loc7`='La batalla por la Cuenca de Arathi comenzará en 30 segundos. ¡Preparaos!' WHERE entry=662;
UPDATE trinity_string SET `content_loc7`='¡La batalla por la Cuenca de Arathi ha comenzado!' WHERE entry=663;
UPDATE trinity_string SET `content_loc7`='¡La Alianza ha reunido $1440W recursos y está cerca de la victoria!' WHERE entry=664;
UPDATE trinity_string SET `content_loc7`='¡La Horda ha reundio $1440W recursos y está cerca de la victoria!' WHERE entry=665;
UPDATE trinity_string SET `content_loc7`='Después de la batalla en %s nuestros intentos por otorgarte la marca de Honor han fracasado. Adjuntamos la marca de Honor que no pudimos entregarte anteriormente. ¡Gracias por luchar en %s!' WHERE entry=666;
UPDATE trinity_string SET `content_loc7`='¡La Alianza ha tomado el control de la Torre de los Magos!' WHERE entry=667;
UPDATE trinity_string SET `content_loc7`='¡La Horda ha tomado el control de la Torre de los Magos!' WHERE entry=668;
UPDATE trinity_string SET `content_loc7`='¡La Alianza ha tomado el control de las Ruinas de los Draenei!' WHERE entry=669;
UPDATE trinity_string SET `content_loc7`='¡La Horda ha tomado el control de las Ruinas de los Draenei!' WHERE entry=670;
UPDATE trinity_string SET `content_loc7`='¡La Alianza ha tomado el control de la Torre de los Elfos de Sangre!' WHERE entry=671;
UPDATE trinity_string SET `content_loc7`='¡La Horda ha tomado el control de la Torre de los Elfos de Sangre!' WHERE entry=672;
UPDATE trinity_string SET `content_loc7`='¡La Alianza ha tomado el control de las Ruinas del Atracador Vil!' WHERE entry=673;
UPDATE trinity_string SET `content_loc7`='¡La Horda ha tomado el control de las Ruinas del Atracador Vil!' WHERE entry=674;
UPDATE trinity_string SET `content_loc7`='¡La Alianza ha perdido el control de la Torre de los Magos!' WHERE entry=675;
UPDATE trinity_string SET `content_loc7`='¡La Horda ha perdido el control de la Torre de los Magos!' WHERE entry=676;
UPDATE trinity_string SET `content_loc7`='¡La Alianza ha perdido el control de las Ruinas de los Draenei!' WHERE entry=677;
UPDATE trinity_string SET `content_loc7`='¡La Horda ha perdido el control de las Ruinas de los Draenei!' WHERE entry=678;
UPDATE trinity_string SET `content_loc7`='¡La Alianza ha perdido el control de la Torre de los Elfos de Sangre!' WHERE entry=679;
UPDATE trinity_string SET `content_loc7`='¡La Horda ha perdido el control de la Torre de los Elfos de Sangre!' WHERE entry=680;
UPDATE trinity_string SET `content_loc7`='¡La Alianza ha perdido el control de las Ruinas del Atracador Vil!' WHERE entry=681;
UPDATE trinity_string SET `content_loc7`='¡La Horda ha perdido el control de las Ruinas del Atracador Vil!' WHERE entry=682;
UPDATE trinity_string SET `content_loc7`='¡%s ha capturado la bandera!' WHERE entry=683;
UPDATE trinity_string SET `content_loc7`='¡La Alianza ha capturado la bandera!' WHERE entry=684;
UPDATE trinity_string SET `content_loc7`='¡La Horda ha capturado la bandera!' WHERE entry=685;
UPDATE trinity_string SET `content_loc7`='¡La bandera ha sido perdida!' WHERE entry=686;
UPDATE trinity_string SET `content_loc7`='La bandera ha sido reinicializada.' WHERE entry=687;
UPDATE trinity_string SET `content_loc7`='Debes tener nivel %u para formar parte de un equipo de arena' WHERE entry=700;
UPDATE trinity_string SET `content_loc7`='¡Un minuto para que la batalla en la Arena de comienzo!' WHERE entry=701;
UPDATE trinity_string SET `content_loc7`='¡Treinta segundos para que la batalla en la Arena de comienzo!' WHERE entry=702;
UPDATE trinity_string SET `content_loc7`='¡Quince segundos para que la batalla en la Arena de comienzo!' WHERE entry=703;
UPDATE trinity_string SET `content_loc7`='¡La batalla en la Arena ha comenzado!' WHERE entry=704;
UPDATE trinity_string SET `content_loc7`='Debes esperar %s antes de hablar de nuevo.' WHERE entry=705;
UPDATE trinity_string SET `content_loc7`='Este objeto(s) tiene problemas al equiparlo/almacenarlo en el inventario.' WHERE entry=706;
UPDATE trinity_string SET `content_loc7`='%s desea no ser molestado y no puede recibir mensajes privados: %s' WHERE entry=707;
UPDATE trinity_string SET `content_loc7`='%s está alejado del teclado desde hace: %s' WHERE entry=708;
UPDATE trinity_string SET `content_loc7`='No molestar' WHERE entry=709;
UPDATE trinity_string SET `content_loc7`='Alejado del Teclado' WHERE entry=710;
UPDATE trinity_string SET `content_loc7`='Estado de cola para %s (Nvl: %u a %u)\nCola en la alianza: %u (Se necesita al menos %u o más)\nCola en la horda: %u (Se necesita al menos %u o más)' WHERE entry=711;
UPDATE trinity_string SET `content_loc7`='|cffff0000[Anuncio de Cola de BG]:|r %s -- [%u-%u] A: %u/%u, H: %u/%u|r' WHERE entry=712;
UPDATE trinity_string SET `content_loc7`='¡Debes ser de nivel %u para unirte a un equipo de arena!' WHERE entry=713;
UPDATE trinity_string SET `content_loc7`='No cumples los requisitos de nivel del campo de batalla' WHERE entry=715;
UPDATE trinity_string SET `content_loc7`='|cffff0000[Anuncio de Cola de BG]:|r %s -- [%u-%u] ¡Comenzado!|r' WHERE entry=717;
UPDATE trinity_string SET `content_loc7`='|cffff0000[Anuncio de Cola de Arena]:|r %s -- Unido : %ux%u : %u|r' WHERE entry=718;
UPDATE trinity_string SET `content_loc7`='|cffff0000[Anuncio de Cola de Arena]:|r %s -- Abandonó : %ux%u : %u|r' WHERE entry=719;
UPDATE trinity_string SET `content_loc7`='Tu grupo es demasiado grande para este campo de batalla. Por favor, reagrúpate para unirte.' WHERE entry=720;
UPDATE trinity_string SET `content_loc7`='Tu grupo es demasiado grande para esta arena. Por favor reagrúpate para unirte.' WHERE entry=721;
UPDATE trinity_string SET `content_loc7`='Tu grupo tiene miembros que no están en tu grupo de arena. Por favor reagrúpate para unirte.' WHERE entry=722;
UPDATE trinity_string SET `content_loc7`='Tu grupo no tiene bastantes jugadores para unirse a este combate.' WHERE entry=723;
UPDATE trinity_string SET `content_loc7`='¡El Equipo Dorado gana!' WHERE entry=724;
UPDATE trinity_string SET `content_loc7`='¡El Equipo Verde gana!' WHERE entry=725;
UPDATE trinity_string SET `content_loc7`='No hay bastantes jugadores en este campo de batalla. Finalizará pronto a menos que se unan más jugadores para equilibrar la lucha.' WHERE entry=726;
UPDATE trinity_string SET `content_loc7`='Tu grupo tiene un miembro desconectado. Por favor expúlsalo antes de unirte.' WHERE entry=727;
UPDATE trinity_string SET `content_loc7`='Tu grupo tiene jugadores de la facción contraria. No puedes unirte al campo de batalla como un grupo.' WHERE entry=728;
UPDATE trinity_string SET `content_loc7`='Tu grupo tiene jugadores de distintos campos de batalla. No puedes unirte como grupo.' WHERE entry=729;
UPDATE trinity_string SET `content_loc7`='Alguien de tu grupo está ya en la cola de este campo de batalla. El(la) tiene que abandonarla antes de unirte como grupo.' WHERE entry=730;
UPDATE trinity_string SET `content_loc7`='Alguien de tu grupo es Desertor. No puedes unirte como grupo.' WHERE entry=731;
UPDATE trinity_string SET `content_loc7`='Alguien de tu grupo está ya en tres colas de campo de batalla. No puedes unirte como grupo.' WHERE entry=732;
UPDATE trinity_string SET `content_loc7`='No puedes teletransportarte a un campo de batalla o mapa de arena.' WHERE entry=733;
UPDATE trinity_string SET `content_loc7`='No puedes invocar jugadores a un campo de batalla o mapa de arena.' WHERE entry=734;
UPDATE trinity_string SET `content_loc7`='Debes estar en modo MJ para teletransportarte a un jugador que esté en un campo de batalla.' WHERE entry=735;
UPDATE trinity_string SET `content_loc7`='No puedes teletransportarte a un campo de batalla desde otro. Por favor abandona el campo de batalla primero.' WHERE entry=736;
UPDATE trinity_string SET `content_loc7`='Las Arenas se han establecido a 1c1 para depuración. No te unas como grupo.' WHERE entry=737;
UPDATE trinity_string SET `content_loc7`='Las Arenas se han establecido a modo normal.' WHERE entry=738;
UPDATE trinity_string SET `content_loc7`='Los Campos de Batalla se han establecido a 1c0 para depuración.' WHERE entry=739;
UPDATE trinity_string SET `content_loc7`='Los Campos de Batalla se han establecido a modo normal.' WHERE entry=740;
UPDATE trinity_string SET `content_loc7`='Calculando puntos de Arena basándose en la clasificación de los equipos, esto puede llevar varios minutos. Por favor espera...' WHERE entry=741;
UPDATE trinity_string SET `content_loc7`='Distribuyendo los puntos de arena a los jugadores...' WHERE entry=742;
UPDATE trinity_string SET `content_loc7`='Finalizada la distribución de puntos para los jugadores conectados.' WHERE entry=743;
UPDATE trinity_string SET `content_loc7`='Modificada la cuenta jugada, puntos de arena, etc. para los equipos de arena cargados, enviando estadísticas actualizadas a los jugadores conectados...' WHERE entry=744;
UPDATE trinity_string SET `content_loc7`='Modificación realizada.' WHERE entry=745;
UPDATE trinity_string SET `content_loc7`='Finalizado el cálculo de puntos de Arena.' WHERE entry=746;
UPDATE trinity_string SET `content_loc7`='Este Campo de Batalla ha sido desactivado. No puedes unirte a la cola.' WHERE entry=747;
UPDATE trinity_string SET `content_loc7`='Las Arenas han sido desactivadas. No puedes unirte a la cola.' WHERE entry=748;
UPDATE trinity_string SET `content_loc7`='No hay suficientes jugadores. Este juego finalizará en %u mins.' WHERE entry=750;
UPDATE trinity_string SET `content_loc7`='No hay suficientes jugadores. Este juego se cerrará en %u segundos.' WHERE entry=751;
UPDATE trinity_string SET `content_loc7`='La batalla por la Garganta Grito de Guerra comenzará en 2 minutos.' WHERE entry=753;
UPDATE trinity_string SET `content_loc7`='La batalla por la Cuenca de Arathi comenzará en 2 minutos.' WHERE entry=754;
UPDATE trinity_string SET `content_loc7`='La batalla por el Ojo de la Tormenta comenzará en 2 minutos.' WHERE entry=755;
UPDATE trinity_string SET `content_loc7`='¡La batalla ha comenzado!' WHERE entry=756;
UPDATE trinity_string SET `content_loc7`='¡La %s ha defendido la Fortaleza de Conquista del Invierno!' WHERE entry=757;
UPDATE trinity_string SET `content_loc7`='¡La %s se ha hecho con el control de la Fortaleza de Conquista del Invierno!' WHERE entry=758;
UPDATE trinity_string SET `content_loc7`='¡El Taller de Asedio de %s ha sido atacado por la %s!' WHERE entry=759;
UPDATE trinity_string SET `content_loc7`='¡El Taller de Asedio de %s ha sido tomado por la %s!' WHERE entry=760;
UPDATE trinity_string SET `content_loc7`='¡Han dañado la torre %s!' WHERE entry=761;
UPDATE trinity_string SET `content_loc7`='¡Han destruido la torre %s!' WHERE entry=762;
UPDATE trinity_string SET `content_loc7`='¡Están atacando Fortaleza de Conquista del Invierno!' WHERE entry=763;
UPDATE trinity_string SET `content_loc7`='La Fortaleza de Conquista del Invierno ahora está bajo el control de la %s.' WHERE entry=764;
UPDATE trinity_string SET `content_loc7`='Tiempo de Conquista del Invierno puesto a %s.' WHERE entry=765;
UPDATE trinity_string SET `content_loc7`='La batalla por Conquista del Invierno ha comenzado.' WHERE entry=766;
UPDATE trinity_string SET `content_loc7`='La batalla por Conquista del Invierno ha finalizado.' WHERE entry=767;
UPDATE trinity_string SET `content_loc7`='Información de Conquista del Invierno: Bajo el control de la %s. Tiempo: %s. Tiempo de guerra: %s. Número de jugadores: (Horda: %u, Alianza: %u)' WHERE entry=768;
UPDATE trinity_string SET `content_loc7`='OutdoorPvP de Conquista del Invierno está deshabilitado.' WHERE entry=769;
UPDATE trinity_string SET `content_loc7`='OutdoorPvP de Conquista del Invierno está habilitado.' WHERE entry=770;
UPDATE trinity_string SET `content_loc7`='Has alcanzado el Rango 1: Cabo' WHERE entry=771;
UPDATE trinity_string SET `content_loc7`='Has alcanzado el Rango 2: Teniente primero' WHERE entry=772;
UPDATE trinity_string SET `content_loc7`='La comprobación de Arena se puso %s' WHERE entry=785;
UPDATE trinity_string SET `content_loc7`='|cffff0000[Automático]:|r' WHERE entry=786;
UPDATE trinity_string SET `content_loc7`='|cffffff00[|c1f40af20Anunciado por|r |cffff0000%s|cffffff00]:|r %s|r' WHERE entry=787;
UPDATE trinity_string SET `content_loc7`='Nombre incorrecto' WHERE entry=800;
UPDATE trinity_string SET `content_loc7`='No tienes suficiente oro' WHERE entry=801;
UPDATE trinity_string SET `content_loc7`='No tienes suficientes espacios libres' WHERE entry=802;
UPDATE trinity_string SET `content_loc7`='Tu compañero no tiene suficientes espacios libres en la bolsa' WHERE entry=803;
UPDATE trinity_string SET `content_loc7`='No tienes permiso para realizar esa función' WHERE entry=804;
UPDATE trinity_string SET `content_loc7`='Idioma desconocido' WHERE entry=805;
UPDATE trinity_string SET `content_loc7`='No conoces ese idioma' WHERE entry=806;
UPDATE trinity_string SET `content_loc7`='Por favor proporciona el nombre del personaje' WHERE entry=807;
UPDATE trinity_string SET `content_loc7`='Jugador %s no encontrado o desconectado' WHERE entry=808;
UPDATE trinity_string SET `content_loc7`='Cuenta del personaje %s no encontrado' WHERE entry=809;
UPDATE trinity_string SET `content_loc7`='¡|Hjugador:$N|h[$N]|h ha conseguido el logro $a!' WHERE entry=810;
UPDATE trinity_string SET `content_loc7`='Maestro de Hermandad' WHERE entry=811;
UPDATE trinity_string SET `content_loc7`='Oficial' WHERE entry=812;
UPDATE trinity_string SET `content_loc7`='Veterano' WHERE entry=813;
UPDATE trinity_string SET `content_loc7`='Miembro' WHERE entry=814;
UPDATE trinity_string SET `content_loc7`='Iniciado' WHERE entry=815;
UPDATE trinity_string SET `content_loc7`='¡Atención: Has entrado en una zona donde no se permite volar y vas a ser desmontado!' WHERE entry=816;
UPDATE trinity_string SET `content_loc7`='La entrada %u no se encuentra en la tabla creature_template.' WHERE entry=817;
UPDATE trinity_string SET `content_loc7`='La entrada %u no se encuentra en sCreatureStorage. Posible nueva línea en creature_template, pero no puedes añadir nuevas criaturas sin reiniciar. Sólo se permite la modificación.' WHERE entry=818;
UPDATE trinity_string SET `content_loc7`='Ciudad' WHERE entry=819;
UPDATE trinity_string SET `content_loc7`='Saliendo...' WHERE entry=1000;
UPDATE trinity_string SET `content_loc7`='Cuenta eliminada: %s' WHERE entry=1001;
UPDATE trinity_string SET `content_loc7`='Cuenta %s NO eliminada (probablemente el formato de archivo sql se ha actualizado)' WHERE entry=1002;
UPDATE trinity_string SET `content_loc7`='Cuenta %s NO eliminada (error desconocido)' WHERE entry=1003;
UPDATE trinity_string SET `content_loc7`='Cuenta creada: %s' WHERE entry=1004;
UPDATE trinity_string SET `content_loc7`='El nombre de la cuenta no puede ser superior a 16 caracteres (límite del cliente), ¡no se creó la cuenta!' WHERE entry=1005;
UPDATE trinity_string SET `content_loc7`='¡Una cuenta con este nombre ya existe!' WHERE entry=1006;
UPDATE trinity_string SET `content_loc7`='Cuenta %s NO creada (probablemente el formato de archivo sql se ha actualizado)' WHERE entry=1007;
UPDATE trinity_string SET `content_loc7`='Cuenta %s no creada (error desconocido)' WHERE entry=1008;
UPDATE trinity_string SET `content_loc7`='Jugador %s (Guid: %u) Cuenta %s (Id: %u) eliminado.' WHERE entry=1009;
UPDATE trinity_string SET `content_loc7`='-[          Cuenta][   Personaje][             IP][Mapa][Zona][Exp][NivMJ]-' WHERE entry=1010;
UPDATE trinity_string SET `content_loc7`='|<Error>        | %20s |<Error>          |<Er>| <Error>   |' WHERE entry=1011;
UPDATE trinity_string SET `content_loc7`='-==================================================================-' WHERE entry=1012;
UPDATE trinity_string SET `content_loc7`='-[%16s][%12s][%15s][%3d][%4d][%d][%d]-' WHERE entry=1013;
UPDATE trinity_string SET `content_loc7`='No hay jugadores conectados.' WHERE entry=1014;
UPDATE trinity_string SET `content_loc7`='-====================== Personajes Conectados =====================-' WHERE entry=1015;
UPDATE trinity_string SET `content_loc7`='| GUID       | Nombre               | Cuenta                       | Fecha Borrado       |' WHERE entry=1016;
UPDATE trinity_string SET `content_loc7`='| %10u | %20s | %15s (%10u) | %19s |' WHERE entry=1017;
UPDATE trinity_string SET `content_loc7`='==========================================================================================' WHERE entry=1018;
UPDATE trinity_string SET `content_loc7`='No se han encontrado personajes.' WHERE entry=1019;
UPDATE trinity_string SET `content_loc7`='Restaurando los personajes siguientes:' WHERE entry=1020;
UPDATE trinity_string SET `content_loc7`='Eliminando los personajes siguientes:' WHERE entry=1021;
UPDATE trinity_string SET `content_loc7`='ERROR: ¡Solo puedes asignar un nuevo nombre si tienes seleccionado un solo personaje!' WHERE entry=1022;
UPDATE trinity_string SET `content_loc7`='Personaje \'%s\' (GUID: %u Cuenta %u) no puede ser restaurado: ¡la cuenta no existe!' WHERE entry=1023;
UPDATE trinity_string SET `content_loc7`='Personaje \'%s\' (GUID: %u Cuenta %u) no puede ser restaurado: ¡la lista de personajes de la cuenta está completa!' WHERE entry=1024;
UPDATE trinity_string SET `content_loc7`='Personaje \'%s\' (GUID: %u Cuenta %u) no puede ser restaurado: ¡el nuevo nombre ya ha sido utilizado!' WHERE entry=1025;
UPDATE trinity_string SET `content_loc7`='GUID: %u Nombre: %s Cuenta: %s (%u) Fecha: %s' WHERE entry=1026;
UPDATE trinity_string SET `content_loc7`='Registro de consulta del controlador SQL activado.' WHERE entry=1027;
UPDATE trinity_string SET `content_loc7`='Registro de consulta del controlador SQL desactivado.' WHERE entry=1028;
UPDATE trinity_string SET `content_loc7`='Cuenta %s (Id: %u) ahora tiene la expansión %u activada.' WHERE entry=1100;
UPDATE trinity_string SET `content_loc7`='El mensaje diario cambió a:\r\n%s' WHERE entry=1101;
UPDATE trinity_string SET `content_loc7`='Mensaje enviado a %s: %s' WHERE entry=1102;
UPDATE trinity_string SET `content_loc7`='%d - %s %s' WHERE entry=1103;
UPDATE trinity_string SET `content_loc7`='%d - %s' WHERE entry=1104;
UPDATE trinity_string SET `content_loc7`='%d - %s' WHERE entry=1105;
UPDATE trinity_string SET `content_loc7`='%d - %s %s' WHERE entry=1106;
UPDATE trinity_string SET `content_loc7`='%d - %s' WHERE entry=1107;
UPDATE trinity_string SET `content_loc7`='%d - %s %s' WHERE entry=1108;
UPDATE trinity_string SET `content_loc7`='%d - %s %s %s %s' WHERE entry=1109;
UPDATE trinity_string SET `content_loc7`='%d - %s X:%f Y:%f Z:%f Id Mapa:%d' WHERE entry=1110;
UPDATE trinity_string SET `content_loc7`='%d - %s X:%f Y:%f Z:%f Id Mapa:%d' WHERE entry=1111;
UPDATE trinity_string SET `content_loc7`='No se ha podido abrir el archivo: %s' WHERE entry=1112;
UPDATE trinity_string SET `content_loc7`='Cuenta %s (%u) tiene el máximo de personajes permitido (límite del cliente)' WHERE entry=1113;
UPDATE trinity_string SET `content_loc7`='¡El archivo de volcado tiene datos corruptos!' WHERE entry=1114;
UPDATE trinity_string SET `content_loc7`='¡Nombre de personaje no válido!' WHERE entry=1115;
UPDATE trinity_string SET `content_loc7`='¡Guid de personaje no válido!' WHERE entry=1116;
UPDATE trinity_string SET `content_loc7`='¡El guid del personaje %u está en uso!' WHERE entry=1117;
UPDATE trinity_string SET `content_loc7`='%d - hermandad: %s (guid: %u) %s' WHERE entry=1118;
UPDATE trinity_string SET `content_loc7`='Debes utilizar masculino (male) o femenino (female) como género.' WHERE entry=1119;
UPDATE trinity_string SET `content_loc7`='Cambiaste el género de %s a %s.' WHERE entry=1120;
UPDATE trinity_string SET `content_loc7`='Tú género cambió de %s a %s.' WHERE entry=1121;
UPDATE trinity_string SET `content_loc7`='(%u/%u +perm %u +temp %u)' WHERE entry=1122;
UPDATE trinity_string SET `content_loc7`='Ninguna mascota encontrada' WHERE entry=1123;
UPDATE trinity_string SET `content_loc7`='Tipo de mascota incorrecta' WHERE entry=1124;
UPDATE trinity_string SET `content_loc7`='Tu mascota aprendió todos los talentos' WHERE entry=1125;
UPDATE trinity_string SET `content_loc7`='Los talentos de tu mascota han sido reiniciados.' WHERE entry=1126;
UPDATE trinity_string SET `content_loc7`='Talentos de la mascota de %s reiniciados.' WHERE entry=1127;
UPDATE trinity_string SET `content_loc7`='%d - |cffffffff|Hrutavuelo:%u|h[%s %s]|h|r (Mapa:%u X:%f Y:%f Z:%f)' WHERE entry=1128;
UPDATE trinity_string SET `content_loc7`='%d - %s %s (Mapa:%u X:%f Y:%f Z:%f)' WHERE entry=1129;
UPDATE trinity_string SET `content_loc7`='No se pueden volcar personajes eliminados, abortando.' WHERE entry=1130;
UPDATE trinity_string SET `content_loc7`='Los personajes siguientes coinciden con tu consulta:' WHERE entry=1131;
UPDATE trinity_string SET `content_loc7`='Personajes baneados actualmente:' WHERE entry=1132;
UPDATE trinity_string SET `content_loc7`='|   Personaje   | Fecha Baneo  |Fecha Desbaneo|  Baneado Por  |  Razón Baneo  |' WHERE entry=1133;
UPDATE trinity_string SET `content_loc7`='Permitido el envío de tickets.' WHERE entry=1134;
UPDATE trinity_string SET `content_loc7`='No permitido el envío de tickets.' WHERE entry=1135;
UPDATE trinity_string SET `content_loc7`='Intentas ver la cinemática %u pero no existe.' WHERE entry=1200;
UPDATE trinity_string SET `content_loc7`='Intentas ver el video %u pero no existe.' WHERE entry=1201;
UPDATE trinity_string SET `content_loc7`='Activado el modo depurador de Areatrigger.' WHERE entry=1202;
UPDATE trinity_string SET `content_loc7`='Desactivado el modo depurador de Areatrigger.' WHERE entry=1203;
UPDATE trinity_string SET `content_loc7`='Has alcanzado el areatrigger %u.' WHERE entry=1204;
UPDATE trinity_string SET `content_loc7`='La batalla comenzará en dos minutos.' WHERE entry=1205;
UPDATE trinity_string SET `content_loc7`='La batalla comenzará en 1 minuto.' WHERE entry=1206;
UPDATE trinity_string SET `content_loc7`='¡La batalla comenzará en 30 segundos!' WHERE entry=1207;
UPDATE trinity_string SET `content_loc7`='¡La batalla ha comenzado!' WHERE entry=1208;
UPDATE trinity_string SET `content_loc7`='la fortaleza de la Alianza' WHERE entry=1209;
UPDATE trinity_string SET `content_loc7`='la fortaleza de la Horda' WHERE entry=1210;
UPDATE trinity_string SET `content_loc7`='¡%s gana!' WHERE entry=1211;
UPDATE trinity_string SET `content_loc7`='¡La puerta oeste de la %s ha sido destruida!' WHERE entry=1212;
UPDATE trinity_string SET `content_loc7`='¡La puerta este de la %s ha sido destruida!' WHERE entry=1213;
UPDATE trinity_string SET `content_loc7`='¡La puerta sur de la %s ha sido destruida!' WHERE entry=1214;
UPDATE trinity_string SET `content_loc7`='¡La puerta norte de la %s ha sido destruida!' WHERE entry=1215;
UPDATE trinity_string SET `content_loc7`='$n ha asaltado %s' WHERE entry=1216;
UPDATE trinity_string SET `content_loc7`='$n ha defendido %s' WHERE entry=1217;
UPDATE trinity_string SET `content_loc7`='¡$n reclama %s! Si no se defiende, ¡la %s tendrá el control en 1 minuto!' WHERE entry=1218;
UPDATE trinity_string SET `content_loc7`='La %s ha tomado %s' WHERE entry=1219;
UPDATE trinity_string SET `content_loc7`='el taller' WHERE entry=1220;
UPDATE trinity_string SET `content_loc7`='los muelles' WHERE entry=1221;
UPDATE trinity_string SET `content_loc7`='la refinería' WHERE entry=1222;
UPDATE trinity_string SET `content_loc7`='la cantera' WHERE entry=1223;
UPDATE trinity_string SET `content_loc7`='el hangar' WHERE entry=1224;
UPDATE trinity_string SET `content_loc7`='Alianza' WHERE entry=1300;
UPDATE trinity_string SET `content_loc7`='Horda' WHERE entry=1301;
UPDATE trinity_string SET `content_loc7`='¡%s fué destruido por la %s!' WHERE entry=1302;
UPDATE trinity_string SET `content_loc7`='¡%s está siendo atacado! Si no se defiende, ¡la %s lo destruirá!' WHERE entry=1303;
UPDATE trinity_string SET `content_loc7`='¡%s ha sido capturado por la %s!' WHERE entry=1304;
UPDATE trinity_string SET `content_loc7`='¡%s ha sido capturado por la %s!' WHERE entry=1305;
UPDATE trinity_string SET `content_loc7`='¡%s ha sido capturado por la %s!' WHERE entry=1306;
UPDATE trinity_string SET `content_loc7`='¡%s está siendo atacado! Si no se defiende, ¡la %s lo capturará!' WHERE entry=1307;
UPDATE trinity_string SET `content_loc7`='¡La %s ha capturado el %s! ¡Sus suministros serán usados para pedir refuerzos!' WHERE entry=1308;
UPDATE trinity_string SET `content_loc7`='Mina Ferrohondo' WHERE entry=1309;
UPDATE trinity_string SET `content_loc7`='Mina Dentefrío' WHERE entry=1310;
UPDATE trinity_string SET `content_loc7`='Puesto de Socorro de Pico Tormenta' WHERE entry=1311;
UPDATE trinity_string SET `content_loc7`='Búnker Sur de Dun Baldar' WHERE entry=1312;
UPDATE trinity_string SET `content_loc7`='Búnker Norte de Dun Baldar' WHERE entry=1313;
UPDATE trinity_string SET `content_loc7`='Cementerio Pico Tormenta' WHERE entry=1314;
UPDATE trinity_string SET `content_loc7`='Búnker de Ala Gélida' WHERE entry=1315;
UPDATE trinity_string SET `content_loc7`='Cementerio Piedrahogar' WHERE entry=1316;
UPDATE trinity_string SET `content_loc7`='Búnker Piedrahogar' WHERE entry=1317;
UPDATE trinity_string SET `content_loc7`='Cementerio Avalancha' WHERE entry=1318;
UPDATE trinity_string SET `content_loc7`='Torre Sangre Fría' WHERE entry=1319;
UPDATE trinity_string SET `content_loc7`='Cementerio Sangre Fría' WHERE entry=1320;
UPDATE trinity_string SET `content_loc7`='Punta de la Torre' WHERE entry=1321;
UPDATE trinity_string SET `content_loc7`='Cementerio Lobo Gélido' WHERE entry=1322;
UPDATE trinity_string SET `content_loc7`='Torre Este Lobo Gélido' WHERE entry=1323;
UPDATE trinity_string SET `content_loc7`='Torre Oeste Lobo Gélido' WHERE entry=1324;
UPDATE trinity_string SET `content_loc7`='Puesto de Auxilio de Lobo Gélido' WHERE entry=1325;
UPDATE trinity_string SET `content_loc7`='La batalla por el Valle de Alterac comenzará en 1 minuto.' WHERE entry=1326;
UPDATE trinity_string SET `content_loc7`='La batalla por el Valle de Alterac comenzará en 30 segundos. ¡Preparaos!' WHERE entry=1327;
UPDATE trinity_string SET `content_loc7`='¡La batalla por el Valle de Alterac ha comenzado!' WHERE entry=1328;
UPDATE trinity_string SET `content_loc7`='¡El equipo de la Alianza se está quedando sin refuerzos!' WHERE entry=1329;
UPDATE trinity_string SET `content_loc7`='¡El equipo de la Horda se está quedando sin refuerzos!' WHERE entry=1330;
UPDATE trinity_string SET `content_loc7`='¡El General Lobo Gélido ha muerto!' WHERE entry=1331;
UPDATE trinity_string SET `content_loc7`='¡El General Pico Tormenta ha muerto!' WHERE entry=1332;
UPDATE trinity_string SET `content_loc7`='La batalla por el Valle de Alterac comenzará en 2 minutos.' WHERE entry=1333;
UPDATE trinity_string SET `content_loc7`='|cff00ff00Nuevo ticket de|r|cffff00ff %s.|r |cff00ff00Entrada ticket:|r|cffff00ff %d.|r' WHERE entry=2000;
UPDATE trinity_string SET `content_loc7`='|cff00ff00Personaje|r|cffff00ff %s |r|cff00ff00editó su ticket:|r|cffff00ff %d.|r' WHERE entry=2001;
UPDATE trinity_string SET `content_loc7`='|cff00ff00Personaje|r|cffff00ff %s |r|cff00ff00entrada de ticket abandonado:|r|cffff00ff %d.|r' WHERE entry=2002;
UPDATE trinity_string SET `content_loc7`='|cff00ff00Cerrado por|r:|cff00ccff %s|r ' WHERE entry=2003;
UPDATE trinity_string SET `content_loc7`='|cff00ff00Eliminado por|r:|cff00ccff %s|r ' WHERE entry=2004;
UPDATE trinity_string SET `content_loc7`='Ticket no encontrado.' WHERE entry=2005;
UPDATE trinity_string SET `content_loc7`='Por favor cierra el ticket antes de eliminarlo permanentemente.' WHERE entry=2006;
UPDATE trinity_string SET `content_loc7`='Ticket %d se encuentra ya asignado.' WHERE entry=2007;
UPDATE trinity_string SET `content_loc7`='%u Tickets cargados correctamente de la base de datos.' WHERE entry=2008;
UPDATE trinity_string SET `content_loc7`='Mostrando lista de tickets abiertos.' WHERE entry=2009;
UPDATE trinity_string SET `content_loc7`='Mostrando lista de tickets abiertos cuyo creador está conectado.' WHERE entry=2010;
UPDATE trinity_string SET `content_loc7`='Mostrando lista de tickets cerrados.' WHERE entry=2011;
UPDATE trinity_string SET `content_loc7`='Especificado nombre incorrecto. El nombre debería ser el de un Maestro de Juego conectado.' WHERE entry=2012;
UPDATE trinity_string SET `content_loc7`='Este ticket se encuentra ya asignado a tí mismo. Para desasignarlo usa .ticket unassign %d y después reasígnalo.' WHERE entry=2013;
UPDATE trinity_string SET `content_loc7`='Ticket %d no se encuentra asignado, no puedes desasignarlo.' WHERE entry=2014;
UPDATE trinity_string SET `content_loc7`='No puedes desasignar tickets de los miembros del personal con un nivel de seguridad superior al tuyo.' WHERE entry=2015;
UPDATE trinity_string SET `content_loc7`='No se puede cerrar el ticket %d, se encuentra asignado a otro MJ.' WHERE entry=2016;
UPDATE trinity_string SET `content_loc7`='|cffaaffaaTicket|r:|cffaaccff %d.|r ' WHERE entry=2017;
UPDATE trinity_string SET `content_loc7`='|cff00ff00Creado por|r:|cff00ccff %s|r ' WHERE entry=2018;
UPDATE trinity_string SET `content_loc7`='|cff00ff00Último cambio|r:|cff00ccff hace %s|r ' WHERE entry=2019;
UPDATE trinity_string SET `content_loc7`='|cff00ff00Asignado a|r:|cff00ccff %s|r ' WHERE entry=2020;
UPDATE trinity_string SET `content_loc7`='|cff00ff00Desasignado por|r:|cff00ccff %s|r ' WHERE entry=2021;
UPDATE trinity_string SET `content_loc7`='|cff00ff00Mensaje Ticket|r: [%s]|r' WHERE entry=2022;
UPDATE trinity_string SET `content_loc7`='|cff00ff00Comentario MJ|r: [%s]|r' WHERE entry=2023;
UPDATE trinity_string SET `content_loc7`='|cff00ccff%s|r |cff00ff00Comentario añadido|r: [%s]|r' WHERE entry=2024;
UPDATE trinity_string SET `content_loc7`='|cff00ff00Creado|r:|cff00ccff hace %s|r ' WHERE entry=2025;
UPDATE trinity_string SET `content_loc7`='Congelaste al jugador %s.' WHERE entry=5000;
UPDATE trinity_string SET `content_loc7`='Puede ser divertido pero no... ¡no puedes congelarte a ti mismo!' WHERE entry=5001;
UPDATE trinity_string SET `content_loc7`='Entrada no válida, comprueba el nombre del objetivo.' WHERE entry=5002;
UPDATE trinity_string SET `content_loc7`='Descongelaste al jugador %s.' WHERE entry=5003;
UPDATE trinity_string SET `content_loc7`='No hay jugadores congelados.' WHERE entry=5004;
UPDATE trinity_string SET `content_loc7`='Los siguientes jugadores se encuentran congelados en el servidor:' WHERE entry=5005;
UPDATE trinity_string SET `content_loc7`='- %s' WHERE entry=5006;
UPDATE trinity_string SET `content_loc7`='Debes estar en un grupo de banda para entrar en esta mazmorra.' WHERE entry=5007;
UPDATE trinity_string SET `content_loc7`='Esta mazmorra está cerrada.' WHERE entry=5008;
UPDATE trinity_string SET `content_loc7`='Sonido %u Reproducido en el servidor' WHERE entry=5009;
UPDATE trinity_string SET `content_loc7`='linkGUID: %u, Entry: %u (%s)' WHERE entry=5010;
UPDATE trinity_string SET `content_loc7`='¡No puedes teletransportarte a tí mismo donde estás!' WHERE entry=5011;
UPDATE trinity_string SET `content_loc7`='¡Ningún mapa encontrado!' WHERE entry=5012;
UPDATE trinity_string SET `content_loc7`='[Continente]' WHERE entry=5013;
UPDATE trinity_string SET `content_loc7`='[Mazmorra]' WHERE entry=5014;
UPDATE trinity_string SET `content_loc7`='[CampoDeBatalla]' WHERE entry=5015;
UPDATE trinity_string SET `content_loc7`='[Arena]' WHERE entry=5016;
UPDATE trinity_string SET `content_loc7`='[Tiempo de reinicio de Banda: %s]' WHERE entry=5017;
UPDATE trinity_string SET `content_loc7`='[Tiempo de reinicio de Heroica: %s]' WHERE entry=5018;
UPDATE trinity_string SET `content_loc7`='[Montable]' WHERE entry=5019;
UPDATE trinity_string SET `content_loc7`='Máscara de fase: %u' WHERE entry=5020;
UPDATE trinity_string SET `content_loc7`='Armadura: %u' WHERE entry=5021;
UPDATE trinity_string SET `content_loc7`='Se otorga la moderación a la primera persona que se una al canal \"%s\": Activado.' WHERE entry=5022;
UPDATE trinity_string SET `content_loc7`='Se otorga la moderación a la primera persona que se una al canal \"%s\": Desactivado.' WHERE entry=5023;
UPDATE trinity_string SET `content_loc7`='Entrada: %u' WHERE entry=5024;
UPDATE trinity_string SET `content_loc7`='Tipo: %u' WHERE entry=5025;
UPDATE trinity_string SET `content_loc7`='ID Display: %u' WHERE entry=5026;
UPDATE trinity_string SET `content_loc7`='Nombre: %s' WHERE entry=5027;
UPDATE trinity_string SET `content_loc7`='ID Despojo: %u' WHERE entry=5028;
UPDATE trinity_string SET `content_loc7`='Alcanzado el límite de resultados (máximos resultados: %d)' WHERE entry=5029;
UPDATE trinity_string SET `content_loc7`='No puedes hablar, gritar o usar emociones hasta que seas de nivel %d.' WHERE entry=6604;
UPDATE trinity_string SET `content_loc7`='No puedes susurrar hasta que llegues al nivel %d.' WHERE entry=6605;
UPDATE trinity_string SET `content_loc7`='No puedes escribir en los canales hasta que llegues al nivel %d.' WHERE entry=6606;
UPDATE trinity_string SET `content_loc7`='No puedes usar la subasta hasta que llegues al nivel %d.' WHERE entry=6607;
UPDATE trinity_string SET `content_loc7`='No puedes abrir tickets hasta que llegues al nivel %d.' WHERE entry=6608;
UPDATE trinity_string SET `content_loc7`='No puedes comerciar hasta que llegues al nivel %d.' WHERE entry=6609;
UPDATE trinity_string SET `content_loc7`='No puedes comerciar con personajes más bajos del nivel %d.' WHERE entry=6610;
UPDATE trinity_string SET `content_loc7`='No puedes enviar correos hasta que llegues al nivel %d.' WHERE entry=6611;
UPDATE trinity_string SET `content_loc7`='No puedes enviar correos a personajes más bajos del nivel %d.' WHERE entry=6612;
UPDATE trinity_string SET `content_loc7`='|cfff00000[Anuncio de MJ]: %s|r' WHERE entry=6613;
UPDATE trinity_string SET `content_loc7`='Notificación a MJs - ' WHERE entry=6614;
UPDATE trinity_string SET `content_loc7`='|cffffff00[|c1f40af20GM Anunciado por|r |cffff0000%s|cffffff00]:|r %s|r' WHERE entry=6615;
UPDATE trinity_string SET `content_loc7`='Silencio está ACTIVADO para %s' WHERE entry=6616;
UPDATE trinity_string SET `content_loc7`='MUNDO: Denegando conexiones.' WHERE entry=7523;
UPDATE trinity_string SET `content_loc7`='MUNDO: Aceptando conexiones.' WHERE entry=7524;
UPDATE trinity_string SET `content_loc7`='¡La Horda ha capturado la Dominancia!' WHERE entry=10001;
UPDATE trinity_string SET `content_loc7`='¡La Alianza ha capturado la Dominancia!' WHERE entry=10002;
UPDATE trinity_string SET `content_loc7`='¡La Horda ha capturado el Estadio!' WHERE entry=10003;
UPDATE trinity_string SET `content_loc7`='¡La Alianza ha capturado el Estadio!' WHERE entry=10004;
UPDATE trinity_string SET `content_loc7`='¡La Horda ha capturado el Cerro Tábido!' WHERE entry=10005;
UPDATE trinity_string SET `content_loc7`='¡La Alianza ha capturado el Cerro Tábido!' WHERE entry=10006;
UPDATE trinity_string SET `content_loc7`='¡La Horda perdió la Dominancia!' WHERE entry=10007;
UPDATE trinity_string SET `content_loc7`='¡La Alianza perdió la Dominancia!' WHERE entry=10008;
UPDATE trinity_string SET `content_loc7`='¡La Horda perdió el Estadio!' WHERE entry=10009;
UPDATE trinity_string SET `content_loc7`='¡La Alianza perdió el Estadio!' WHERE entry=10010;
UPDATE trinity_string SET `content_loc7`='¡La Horda perdió el Cerro Tábido!' WHERE entry=10011;
UPDATE trinity_string SET `content_loc7`='¡La Alianza perdió el Cerro Tábido!' WHERE entry=10012;
UPDATE trinity_string SET `content_loc7`='¡La Horda ha capturado la Baliza Oeste!' WHERE entry=10013;
UPDATE trinity_string SET `content_loc7`='¡La Alianza ha capturado la Baliza Oeste!' WHERE entry=10014;
UPDATE trinity_string SET `content_loc7`='¡La Horda ha capturado la Baliza Este!' WHERE entry=10015;
UPDATE trinity_string SET `content_loc7`='¡La Alianza ha capturado la Baliza Este!' WHERE entry=10016;
UPDATE trinity_string SET `content_loc7`='¡La Horda ha capturado el Cementerio de las Agujas Gemelas!' WHERE entry=10017;
UPDATE trinity_string SET `content_loc7`='¡La Alianza ha capturado el Cementerio de las Agujas Gemelas!' WHERE entry=10018;
UPDATE trinity_string SET `content_loc7`='¡La Horda perdió la Baliza Oeste!' WHERE entry=10019;
UPDATE trinity_string SET `content_loc7`='¡La Alianza perdió la Baliza Oeste!' WHERE entry=10020;
UPDATE trinity_string SET `content_loc7`='¡La Horda perdió la Baliza Este!' WHERE entry=10021;
UPDATE trinity_string SET `content_loc7`='¡La Alianza perdió la Baliza Este!' WHERE entry=10022;
UPDATE trinity_string SET `content_loc7`='¡La Horda perdió el Cementerio de las Agujas Gemelas!' WHERE entry=10023;
UPDATE trinity_string SET `content_loc7`='¡La Alianza perdió el Cementerio de las Agujas Gemelas!' WHERE entry=10024;
UPDATE trinity_string SET `content_loc7`='¡La Horda ha capturado Halaa!' WHERE entry=10025;
UPDATE trinity_string SET `content_loc7`='¡La Alianza ha capturado Halaa!' WHERE entry=10026;
UPDATE trinity_string SET `content_loc7`='¡La Horda perdió Halaa!' WHERE entry=10027;
UPDATE trinity_string SET `content_loc7`='¡La Alianza perdió Halaa!' WHERE entry=10028;
UPDATE trinity_string SET `content_loc7`='¡La Horda ha capturado la Torre del Espíritu!' WHERE entry=10029;
UPDATE trinity_string SET `content_loc7`='¡La Alianza ha capturado la Torre del Espíritu!' WHERE entry=10030;
UPDATE trinity_string SET `content_loc7`='¡La Horda perdió la Torre del Espíritu!' WHERE entry=10031;
UPDATE trinity_string SET `content_loc7`='¡La Alianza perdió la Torre del Espíritu!' WHERE entry=10032;
UPDATE trinity_string SET `content_loc7`='¡La Horda ha capturado la Torre del Paso Norte!' WHERE entry=10033;
UPDATE trinity_string SET `content_loc7`='¡La Alianza ha capturado la Torre del Paso Norte!' WHERE entry=10034;
UPDATE trinity_string SET `content_loc7`='¡La Horda ha capturado la Torre de la Muralla del Este!' WHERE entry=10035;
UPDATE trinity_string SET `content_loc7`='¡La Alianza ha capturado la Torre de la Muralla del Este!' WHERE entry=10036;
UPDATE trinity_string SET `content_loc7`='¡La Horda ha capturado la Torre de la Corona!' WHERE entry=10037;
UPDATE trinity_string SET `content_loc7`='¡La Alianza ha capturado la Torre de la Corona!' WHERE entry=10038;
UPDATE trinity_string SET `content_loc7`='¡La Horda ha capturado la Torre del Bosque de la Peste!' WHERE entry=10039;
UPDATE trinity_string SET `content_loc7`='¡La Alianza ha capturado la Torre del Bosque de la Peste!' WHERE entry=10040;
UPDATE trinity_string SET `content_loc7`='¡La Horda perdió la Torre del Paso Norte!' WHERE entry=10041;
UPDATE trinity_string SET `content_loc7`='¡La Alianza perdió la Torre del Paso Norte!' WHERE entry=10042;
UPDATE trinity_string SET `content_loc7`='¡La Horda perdió la Torre de la Muralla del Este!' WHERE entry=10043;
UPDATE trinity_string SET `content_loc7`='¡La Alianza perdió la Torre de la Muralla del Este!' WHERE entry=10044;
UPDATE trinity_string SET `content_loc7`='¡La Horda perdió la Torre de la Corona!' WHERE entry=10045;
UPDATE trinity_string SET `content_loc7`='¡La Alianza perdió la Torre de la Corona!' WHERE entry=10046;
UPDATE trinity_string SET `content_loc7`='¡La Horda perdió la Torre del Bosque de la Peste!' WHERE entry=10047;
UPDATE trinity_string SET `content_loc7`='¡La Alianza perdió la Torre del Bosque de la Peste!' WHERE entry=10048;
UPDATE trinity_string SET `content_loc7`='¡La Horda ha recolectado 200 de silitista!' WHERE entry=10049;
UPDATE trinity_string SET `content_loc7`='¡La Alianza ha recolectado 200 de silitista!' WHERE entry=10050;
UPDATE trinity_string SET `content_loc7`='Llévame a la Torre del Paso Norte.' WHERE entry=10051;
UPDATE trinity_string SET `content_loc7`='Llévame a la Torre de la Muralla del Este.' WHERE entry=10052;
UPDATE trinity_string SET `content_loc7`='Llévame a la Torre de la Corona.' WHERE entry=10053;
UPDATE trinity_string SET `content_loc7`='¡Dame la bandera, la llevaré a la Baliza Central por la gloria de la Alianza!' WHERE entry=10054;
UPDATE trinity_string SET `content_loc7`='¡Dame la bandera, la llevaré a la Baliza Central por la gloria de la Horda!' WHERE entry=10055;
UPDATE trinity_string SET `content_loc7`='La batalla por la Playa de los Ancestros comenzará en 2 minutos.' WHERE entry=10056;
UPDATE trinity_string SET `content_loc7`='La batalla por la Playa de los Ancestros comenzará en 1 minuto.' WHERE entry=10057;
UPDATE trinity_string SET `content_loc7`='La batalla por la Playa de los Ancestros comenzará en 30 segundos. ¡Preparáos!.' WHERE entry=10058;
UPDATE trinity_string SET `content_loc7`='¡La batalla por la Playa de los Ancestros ha comenzado!' WHERE entry=10059;
UPDATE trinity_string SET `content_loc7`='¡%s está siendo atacado!' WHERE entry=10060;
UPDATE trinity_string SET `content_loc7`='¡%s está destruido!' WHERE entry=10061;
UPDATE trinity_string SET `content_loc7`='¡Ronda 1 -  finalizada!' WHERE entry=10062;
UPDATE trinity_string SET `content_loc7`='¡La Alianza capturó el Portal de los Ancestros!' WHERE entry=10063;
UPDATE trinity_string SET `content_loc7`='¡La Horda capturó el Portal de los Ancestros!' WHERE entry=10064;
UPDATE trinity_string SET `content_loc7`='La Ronda 2 de la batalla por la Playa de los Ancestros comenzará en 1 minuto.' WHERE entry=10065;
UPDATE trinity_string SET `content_loc7`='La Ronda 2 comenzará en 30 segundos. ¡Preparáos!' WHERE entry=10066;
UPDATE trinity_string SET `content_loc7`='¡Se ha abierto una brecha en la cámara! ¡La Relíquia de los Ancestros es vulnerable!' WHERE entry=10067;
UPDATE trinity_string SET `content_loc7`='¡La Alianza capturó el Cementerio Sur!' WHERE entry=10068;
UPDATE trinity_string SET `content_loc7`='¡La Alianza capturó el Cementerio Oeste!' WHERE entry=10069;
UPDATE trinity_string SET `content_loc7`='¡La Alianza capturó el Cementerio Este!' WHERE entry=10070;
UPDATE trinity_string SET `content_loc7`='¡La Horda capturó el Cementerio Sur!' WHERE entry=10071;
UPDATE trinity_string SET `content_loc7`='¡La Horda capturó el Cementerio Oeste!' WHERE entry=10072;
UPDATE trinity_string SET `content_loc7`='¡La Horda capturó el Cementerio Este!' WHERE entry=10073;
UPDATE trinity_string SET `content_loc7`='|cffffff00[|c00077766Autodifusión|cffffff00]: |cFFF222FF%s|r' WHERE entry=11000;
UPDATE trinity_string SET `content_loc7`='No has elegido -1 o el realmID actual en el que te encuentras.' WHERE entry=11001;
